### ISSUE TITLE
Project Blackduck Vulnerabilities found in serenity js

### ISSUE THREAD

**Issue by nbarrett** [serenity-js/serenity-js#1062]
Hi @jan-molak ! Long time no speak. It seems that my current project is considering moving to Serenity-js + WebdriverIO but in order to do that, we need to assess the vulnerability impact. So our team has run v2.32.3 through our internal blackduck scanning and have found the following Vulnerabilities:
![image](https://user-images.githubusercontent.com/626941/143483333-d4a3875b-26ec-4371-abc6-75d0cc1e19ed.png)

And the following Operational Risks:

![image](https://user-images.githubusercontent.com/626941/143483397-2049dea8-21fa-4163-87e5-d1bc1e25d80a.png)

Right now we are focussed on the vulnerabilities and are wondering whether it might be possible to upgrade the project dependencies to resolve these? Maybe I can help with a PR, once I work out where these dependencies are coming from. I enclose an excel sheet of the affected libraries and the specific vulnerabilities:

[blackduck-vulnerability-report.xlsx](https://github.com/serenity-js/serenity-js/files/7604680/blackduck-vulnerability-report.xlsx)

I look forward to hearing from you and hopefully contributing....

Thanks, @nbarrett

**Comment by jan-molak** [comment]
Hey @nbarrett! Sure thing, I've just released 2.32.4 with updated dependencies, so it would be good to know what Blackduck thinks about those?

I don't think Serenity/JS depends on any of the libs from your Excel spreadsheet directly, but if you could figure out what's pulling them in I'm sure we can figure out how to upgrade them.

**Comment by nbarrett** [comment]
Hi @jan-molak ! - thanks for your quick response - I've just got our security team to re-run the blackduck scan on `Serenity-js-2.32.4` and it seems to have exactly the same vulnerabilities as the prior version. I have captured an additional column showing how the vulnerability was matched and included that as a new **Matched from** column and attach here - hope this helps:

[blackduck-vulnerability-report.xlsx](https://github.com/serenity-js/serenity-js/files/7628261/blackduck-vulnerability-report.xlsx)

I've not had a chance to perform the same on the 3.0 branch yet. We'll have a look to see how easy it is to do that... Cheers :-)

**Comment by jan-molak** [comment]
Hi @nbarrett - `3.0.0-rc.x` is now on npm.

And I have also done a bit of research via `npm ls <module-name>`


## `json-schema` `0.2.3`

This is pulled in via `http-signature`, which is a transitive dependency of `@serenity-js/local-server` **DEV** dependency - `restify` (not used in the production code):

```
└─┬ restify@8.6.0 extraneous
  └─┬ http-signature@1.2.0
    └─┬ jsprim@1.4.1
      └── json-schema@0.2.3
```

To **fix** this issue properly, [`restify`](https://github.com/restify/node-restify) would need a PR to update `http-signature` to `1.3.6` or newer, since that module pulls in a newer `jsprim`, which then depends on `json-schema` `0.4.0`.

To work around it, `@serenity-js/local-server` could override the version of `http-signature` since `resify depends on a version range.

## `yargs-parser` `2.4.1`

This is pulled in via `instanbul-merge`, which is a **DEV** dependency used as part of the Serenity/JS CI/CD pipeline (not used in the production code):

```
├─┬ istanbul-merge@1.1.1
│ └─┬ yargs@4.8.1
│   └── yargs-parser@2.4.1
```

To **fix** this issue properly, [`istanbul-merge`](https://github.com/ljharb/istanbul-merge) would need a PR to update `yargs` to the latest version.

I don't see any obvious workaround.

## `lodash` `4.17.21`

This is the latest version of `lodash`, which is used by several **DEV** dependencies and the vulnerability is being disputed.

However, `lodash` is also used by `port-finder` `2.x` (via `async`), which is a **PROD** dependency of `@serenity-js/local-server`.

To **fix** this issue properly, [`portfinder`](https://github.com/http-party/node-portfinder/) needs a PR to update `async` to `3.x`, which doesn't depend on `lodash`

**Comment by nbarrett** [comment]
Hi @jan-molak - sure thing - I'll raise those 3 PRs forthwith - thanks for your analysis!

**Comment by nbarrett** [comment]
Hi @jan-molak - I've raised 2 of the 2 PRs you suggested but having trouble with bumping the `portfinder` dependency on `async` from `^2.6.2` to `^3.2.2`. When update the npm dependencies and run `npm run test` I get this error in `vows` (the test framework for the project):

```
> portfinder@1.0.28 test /Users/nickbarrett/dev/node-portfinder
> vows test/*-test.js --spec

 
  ♢ portfinder 
  
/Users/nickbarrett/dev/node-portfinder/node_modules/vows/lib/vows.js:208
        util.puts(console.result(results));
             ^

TypeError: util.puts is not a function
    at process.<anonymous> (/Users/nickbarrett/dev/node-portfinder/node_modules/vows/lib/vows.js:208:14)
    at process.emit (events.js:314:20)
    at process.options.Emitter.emit (/Users/nickbarrett/dev/node-portfinder/node_modules/vows/lib/vows.js:241:24)
```

This looks to me to be a problem with using a deprecated library `util` in node but not too sure how to upgrade this as a change now looks to be needed in `vows` which is already at the latests version. Any suggestions appreciated please! 🤞

**Comment by jan-molak** [comment]
Thanks, @nbarrett!

I had a quick look at [`portfinder`](https://github.com/http-party/node-portfinder).
It looks like [its CI pipeline](https://github.com/http-party/node-portfinder/blob/736e98290c5d404bfc8d68748fc14589b989c4cd/.travis.yml#L4-L6) supports `0.12`, `4.2` and `5.0`, so given `4.2` is the only LTS in that mix, I'd try with that for the PR.

It seems like @eriktrom is interested in dropping support for the ancient Node 0.10.x altogether (https://github.com/http-party/node-portfinder/issues/122). 
The maintainers mentioned that the project is locked for any new features (https://github.com/http-party/node-portfinder/pull/117#issuecomment-889402421), but I'm hoping that they'll consider a security fix.

**Comment by jan-molak** [comment]
Hey @nbarrett!

I think we can close this ticket now, as at the time of writing Serenity/JS:
- depends on `restify` `11.1.0`, which no longer depends on the vulnerable `json-schema`
- no longer depends on `istanbul-merge`, 
- depends on the latest version of `portfinder`, which updated its dependency on `async` in http-party/node-portfinder#126
- no longer depends on ESDoc, which means it doesn't have to depend on `ansi-regex`, `nth-check`, `css-what`, or `minimist`

Please let me know if you come across any other issues in the future!
