### ISSUE TITLE
Unable to find a way to create extra children with restQuery in the final report

### ISSUE THREAD

**Issue by aukevanleeuwen** [serenity-js/serenity-js#1239]
I've had the pleasure of working with Cucumber-JVM combined with Serenity in the past and am now using the cucumber.js and serenity-js it in a TypeScript project. I'm still figuring out the differences a bit obviously, but one of the things I haven't been able to figure out is how to get extra 'children' - specifically with `restQuery` to end up in the reports.

Now matter what I try with `World#attach()` or `World#log()`, it doesn't seem to end up in the report.

Basically I only get one 'level' of steps in the resulting JSON like this:

```json
    ...
    "testSteps": [
        {
            "number": 1,
            "description": "Given a carrier Xxxx with valid OAuth credentials",
            "startTime": 1657348150985,
            "children": [],
            "reportData": [],
            "screenshots": [],
            "duration": 385,
            "result": "SUCCESS"
        },
        {
            "number": 2,
            ...
```

This will give me something like this: 
![image](https://user-images.githubusercontent.com/301092/178095149-c2e3de4c-1aab-4dc7-bb88-bb187147950a.png)

But if I manually insert a child with a `restQuery` field:

```json
    ...
    "testSteps": [
        {
            "number": 1,
            "description": "Given a carrier Xxxx with valid OAuth credentials",
            "startTime": 1657348150985,
            "children": [
                {
                    "number": 2,
                    "description": "POST https://test-auth.example.com/oauth/token/",
                    "duration": 0,
                    "startTime": "2021-12-23T15:37:26.511641+01:00[Europe/Amsterdam]",
                    "result": "SUCCESS",
                    "restQuery": {
                        "method": "POST",
                        "path": "https://test-auth.example.com/oauth/token/",
                        "content": "{\n    \"audience\": \"https://api.example.com/something/\",\n    \"scope\": \"openid profile email\",\n    <truncated>}",
                        "contentType": "application/json",
                        "requestHeaders": "Accept=*/*\n\t\t\t\tContent-Type=application/json; charset=UTF-8",
                        "requestCookies": "",
                        "responseHeaders": "Date: Thu, 23 Dec 2021 14:37:26 GMT\nContent-Type: application/json\nTransfer-Encoding: chunked\nConnection: keep-alive",
                        "responseCookies": "...",
                        "responseBody": "{\n    \"access_token\": \"some-token\",\n    \"scope\": \"openid profile email\",\n    \"expires_in\": 86400,\n    \"token_type\": \"Bearer\"\n}",
                        "statusCode": 200
                    },
                    "precondition": false,
                    "level": 1
                }
            ],
            "reportData": [],
            "screenshots": [],
            "duration": 385,
            "result": "SUCCESS"
        },
        {
            "number": 3,

```

I can expand the first step all the way up until the REST query even:

![image](https://user-images.githubusercontent.com/301092/178095341-46ec3d77-aa8a-4fbe-bf1a-0ac701828412.png)

(The dates etc don't match up, because I copied the example over from some time ago (from a JVM based report))

So the question is: if this is supported currently. Thanks in advance.

**Comment by jan-molak** [comment]
Hi @aukevanleeuwen and welcome :-)

So if I understand correctly, what you're after is being able to see the request/response data in the report is that right?

Are you using [`@serenity-js/rest` module](https://serenity-js.org/modules/rest/)? It should be attaching this data by default.

**Comment by aukevanleeuwen** [comment]
Hey @jan-molak, no I'm not actually. I might look into this later, but for now it's a bit too much of a burden to wrap my head around the whole screenplay thing. Most examples are about web-based end-to-end testing, whereas i'm testing a pure API based platform with several (instructable) [mockservers](https://mock-server.com/) and http clients as actors. 

_Maybe_ it would still work anyway, but right now I started with a more plain 'cucumber-js' based implementation that I know how to structure, but I'm using the `@serenity-js/cucumber` reporter to get this nice reports.

So maybe it cannot be easily done with that combination (i.e. _not_ using the `serenity-js/rest` module), but I thought I'd ask the question.

**Comment by jan-molak** [comment]
Got it, have a look at [this example implementation](https://github.com/serenity-js/serenity-js/tree/master/examples/cucumber-rest-api-level-testing) and let me know if that helps?

**Comment by aukevanleeuwen** [comment]
@jan-molak thanks for the pointer. I will have a good look into that module a bit later on. Right now I already have a bunch of code myself that uses 'plain' `cucumber-js` with [pactum](https://github.com/pactumjs/pactum) to do (and verify) the API requests, so I was just looking at a way to get a `ActivityRelatedArtifactGenerated` into the report with a `HTTPRequestResponse` artifact.

This works: 

```typescript
        serenity.announce(
            new ActivityRelatedArtifactGenerated( // prettier
                serenity.currentSceneId(),
                (serenity as unknown as { stage: Stage }).stage.currentActivityId(),
                Name.fromJSON('some name here'),
                HTTPRequestResponse.fromJSON({
                    request: {
                        method: 'get',
                        url: 'https://myapp.com/api/products/2',
                        headers: { Accept: 'application/json, text/plain, */*' },
                    },
                    response: {
                        status: 200,
                        headers: {
                            'Content-Type': 'application/json',
                        },
                        data: { id: 2 },
                    },
                }),
                serenity.currentTime(),
            ),
        );
```
But I could be breaking a few abstractions here. A couple of things stand out, maybe you have some thoughts on them:
* In general: `stage` is private on the `Serenity` object (and thus also on the `serenity` 'singleton'). I'm guessing you did that on purpose? If not, it would help me at least to make that accessible. I could probably work around that in a very nasty way wrapping the `SerenityBDDReporter` and assigning the stage somewhere accessible to me when `#assignedTo` is called in the `serenity.configure(...)`. But it's rather hacky.  

* `currentActivityId` isn't exposed via the `serenity` singleton. Hence the `(serenity as unknown as { stage: Stage }).stage.currentActivityId()`, is it intentionally hidden as well? Obviously if `stage` would be exposed like above I wouldn't need this, I could use `serenity.stage.currentActivityId()`.

* Even though `Serenity#announce(event: DomainEvent)` is exported/public via `@serenity-js/core`, all of the events I have to get from `import { DomainEvent, ... } from '@serenity-js/core/lib/events'`. So far I've seen (in your code) that you're often re-exporting stuff all the way up to the 'root' of the package I was wondering if you missed a `export * from './events';` in `packages/core/src/index.ts`.

* The above also goes for some stuff from `@serenity-js/core/lib/model` btw (in my case `HTTPRequestResponse` and `Name`).

Btw: although I haven't wrapped my head around all of it (yet), your code looks super clean and well structured. Great job, that alone makes me want to have a look at how to use the rest of the framework (i.e. with the example that you gave). But for now I don't have time to rewrite it yet.

**Comment by jan-molak** [comment]
Hey @aukevanleeuwen! Cool, I see you've dived deep into this :-)

> In general: stage is private on the Serenity object (and thus also on the serenity 'singleton'). I'm guessing you did that on purpose? 

Yes, this is intentional. Serenity object is the only singleton in the framework and is responsible for managing access to actors, registering stage crew members (services)

> If not, it would help me at least to make that accessible. I could probably work around that in a very nasty way wrapping the SerenityBDDReporter and assigning the stage somewhere accessible to me when #assignedTo is called in the serenity.configure(...). But it's rather hacky.

Yes, it would be totally hacky :-) You don't have to do that, though.

A slightly less hacky way would be to use:

```diff
- (serenity as unknown as { stage: Stage }).stage.currentActivityId(),
+ serenity.assignNewActivityId()
```

But there's an even better and more idiomatic way. Bear with me :)

> currentActivityId isn't exposed via the serenity singleton. Hence the (serenity as unknown as { stage: Stage }).stage.currentActivityId(), is it intentionally hidden as well? Obviously if stage would be exposed like above I wouldn't need this, I could use serenity.stage.currentActivityId().


From what I understand, the only reason you need access to `Stage` is to get an activity id. 

However, using `currentActivityId` from outside of an actor is a bit risky since you can't be sure if there _is_ an `activityId` available, and if it is, if it's the one you actually want to attach an artifact to (i.e. we don't know what "current" means in this context).

A better and more idiomatic API to use is `actor.collect()`, which relies on the fact that an actor has access to the stage: 

https://github.com/serenity-js/serenity-js/blob/3eb059a552b02c3ef7ee3cf2d8dcaaba9fcb2059/packages/core/src/screenplay/actor/Actor.ts#L157-L165

The way it works is that when you call `actor.attemptsTo(...activities)` in the test scenario, actor wraps every activity you provided into a `TrackedActivity`: 
https://github.com/serenity-js/serenity-js/blob/3eb059a552b02c3ef7ee3cf2d8dcaaba9fcb2059/packages/core/src/screenplay/actor/Actor.ts#L76-L78

And this `TrackedActivity` takes care of assigning the current activity id and obtaining the current scene id: 
https://github.com/serenity-js/serenity-js/blob/3eb059a552b02c3ef7ee3cf2d8dcaaba9fcb2059/packages/core/src/screenplay/activities/TrackedActivity.ts#L22-L25

Since `TrackedActivity` has already ensured that the ids are available, interactions like `Send` can invoke `actor.collect` without worrying about the IDs:

https://github.com/serenity-js/serenity-js/blob/3eb059a552b02c3ef7ee3cf2d8dcaaba9fcb2059/packages/rest/src/screenplay/interactions/Send.ts#L64-L78

This design works quite well if a given integration also follows the [Screenplay Pattern](https://serenity-js.org/handbook/design/screenplay-pattern.html).

So for example, if you wanted Serenity/JS to support Pactum (which looks very cool, by the way!), you'd have a Pactum-specific integration module, like `serenity-js-pactum` or `@serenity-js/pactum`.

This module would provide:
- an ability for an actor to `SpecifyPacts.using(pactum)` (or some more appropriate name :-) Have a look at [CallAnApi](https://github.com/serenity-js/serenity-js/blob/main/packages/rest/src/screenplay/abilities/CallAnApi.ts#L92)) 
- some interaction to define the pacts, which calls `pactum.spec()` under the hood
- some way to retrieve the response so that it can be plugged into `@serenity-js/assertions` module

A rough sketch might look like this:

```typescript
const pactum = require('pactum');

actorCalled('Alice')
  .whoCan(SpecifyPacts.using(pactum))
  .attemptsTo(
    SpecifyPact.with(
      method: 'GET',
      url: ...
      headers: ...
      
    )
    .expect(
      status: 200
      
    )
  )
```
Or something akin to `@serenity-js/rest`

```typescript
const pactum = require('pactum');

actorCalled('Alice')
  .whoCan(SpecifyPacts.using(pactum))
  .attemptsTo(
    SpecifyPact.with(GetRequest.to(...))
      .expectations(...)
  )
```

In this model, an interaction to `SpecifyPact` would be performed by an actor, which means that an actor would wrap it into a `TrackedActivity`, and from there you simply call `actor.collect` in `SpecifyPact`.

If you are interested in exploring that I'd be happy to guide you?

> Even though Serenity#announce(event: DomainEvent) is exported/public via @serenity-js/core, all of the events I have to get from import { DomainEvent, ... } from '@serenity-js/core/lib/events'. So far I've seen (in your code) that you're often re-exporting stuff all the way up to the 'root' of the package I was wondering if you missed a export * from './events'; in packages/core/src/index.ts. The above also goes for some stuff from @serenity-js/core/lib/model btw (in my case HTTPRequestResponse and Name).

That's right. The only reason I did that is that I didn't want to pollute the main entry point with types that the vast majority of developers will never use directly. As you can imagine, there are substantially more people using Serenity/JS to write tests than extending/maintaining the framework :-)

Also, I did that before Node had support for multiple entry points in a module.
Once I get some time to look into migrating Serenity/JS to use ES modules, I'll probably rename `@serenity-js/core/lib/events` and `@serenity-js/core/lib/models` to something like `@serenity-js/core/internal` or `@serenity-js/core/integration` so that there is an "official" integration-specific entry point that is separate from the main one, optimised for people who write tests.

**Comment by aukevanleeuwen** [comment]
Thank you for your elaborate comment. I will have a look into the solution above. Unfortunately for the short term I'm really not able to rewrite what I already had. I wanted to use something like `pactum` (actually coming from Java I'm missing [RestAssured](https://rest-assured.io/) a bit) but I didn't see how I could fit that into the screenplay model the way you just showed. I need to have a good look at it, also in relation to how the state is managed¹.

For this issues specifically: I think it can be closed. I've now covered my use case as follows: `pactum` exposes a global way to attach an 'event handler' after any spec interaction. In that handler (which get's all the spec data) I'm doing the following:

```typescript
function recordSpecActivity(stage: Stage, data: SpecData): void {
    stage.assignNewActivityId();

    const interactionDetails = new ActivityDetails(new Name(`${data.request.method.toUpperCase()} ${data.request.url}`));

    try {
        serenity.announce(
            new InteractionStarts(stage.currentSceneId(), stage.currentActivityId(), interactionDetails, new Timestamp(new Date(parseInt(data.start)))),
        );

        // announce a request/response based artifact to Serenity, so it will be attached to the Serenity report
        serenity.announce(
            new ActivityRelatedArtifactGenerated(
                stage.currentSceneId(),
                stage.currentActivityId(),
                new Name(data.name ?? data.id),
                requestResponseArtifactFromSpecData(data),
                stage.currentTime(),
            ),
        );
    } finally {
        serenity.announce(
            new InteractionFinished(
                stage.currentSceneId(),
                stage.currentActivityId(),
                interactionDetails,
                new ExecutionSuccessful(),
                new Timestamp(new Date(parseInt(data.end))),
            ),
        );
    }
}
```

This could theoretically be done with the `serenity` global object, but I'm missing the `currentActivityId()` which I think I need because I need the same activityId in both the `InteractionStarts`, `ActivityRelatedArtifactGenerated` and `InteractionFinished`.

Result is this a collapsed step:

![image](https://user-images.githubusercontent.com/301092/180161577-58bab338-07b9-4e83-ada0-82fd6a9d3a54.png)

which can be expanded to:

![image](https://user-images.githubusercontent.com/301092/180161648-f6688290-701d-4ac6-91b6-a95b43cafc04.png)

Which works awesome. Thanks again for the project!

¹ it's not too easy to describe exactly how I'm managing that now, but it roughly boils down to having actors (I coincidentally called them actors as well) that expose both functionality (i.e. a `createReservation(...)` that issues a HTTP request somewhere) *and* state. Actors are 'attached' to the custom World object. I have defined `ParameterTypes` to  quickly fetch actors based on some identifiers, so I can use `Given('{someActor} does something', function(someActor: SomeActor) {})`.

**Comment by jan-molak** [comment]
Cool, glad you got it to work and thanks for the update! One suggestion:

```diff
function recordSpecActivity(stage: Stage, data: SpecData): void {
-    stage.assignNewActivityId();
+    const activityId = stage.assignNewActivityId();
```
and then you can replace calls to `stage.currentActivityId` with `activityId`

Regarding state management, the developer-accessible state in Serenity/JS actors is represented using a concept called a `Notepad` (so actors can take "notes" of interesting things as they go about their work) - check out the [examples here](https://github.com/serenity-js/serenity-js/blob/master/documentation/website/src/handbook/release-notes/serenity-js-3.md#taking-notes).
Apart from that, every ability can have its own state, since an ability is instantiated for a specific actor and discarded when the actor is dismissed. For example, the ability to `CallAnApi` holds on to the `lastResponse`,

Glad you found Serenity/JS useful, by the way. Let me know if you find things that could be improved or if you'd like to collaborate on making some of those improvements happen :-)
