### ISSUE TITLE
Getting The "path" argument must be of type string. Received null [failsafe] Script 'test:report' exited with code 1 with Serenity bdd report

### ISSUE THREAD

**Issue by SivaAdaveni91** [serenity-js/serenity-js#1455]
Hi,
we are started using "Serenity Bdd Report" in webdriverIO mocha project.
But, getting below error:
[test:report] > ssense-e2e@1.0.0 test:report
[test:report] > serenity-bdd run
[test:report]
[test:report] I'm terribly sorry, but something didn't go according to plan:
[test:report] The "path" argument must be of type string. Received null
[failsafe] Script 'test:report' exited with code 1

package,json:
 "@serenity-js/core": "^3.0.0-rc.37",
    "@serenity-js/serenity-bdd": "^3.0.0-rc.37",
    "npm-failsafe": "^0.4.3",
    "@types/chai": "^4.3.3",
    "rimraf": "^3.0.2",
    
    

wdio,base.conf.ts:

import { configure, ArtifactArchiver } from '@serenity-js/core';
import { SerenityBDDReporter } from '@serenity-js/serenity-bdd';

crew: [
    new SerenityBDDReporter(),
    ArtifactArchiver.storingArtifactsAt('./target/site/serenity'),
],

**Comment by jan-molak** [comment]
Hi @SivaAdaveni91! 

This issue seems similar to #802. Serenity BDD reporter is a Java program and requires Java Runtime Environment version 8 or newer, as per the [installation instructions](https://serenity-js.org/handbook/reporting/serenity-bdd-reporter#installation).

The error message `The "path" argument must be of type string. Received null` bubbles up from one of Serenity/JS dependencies responsible for detecting the location of your Java Runtime Environment (JRE). Since the JRE can't be found, the error is thrown.

However, the way this message is phrased is not great and can be confusing to developers using Serenity/JS, so let me fix that :-)

**Comment by jan-molak** [comment]
@SivaAdaveni91 - fix available in version [`3.0.0-rc.38`](https://github.com/serenity-js/serenity-js/releases/tag/v3.0.0-rc.38)
