### ISSUE TITLE
Unable to use Serenity/JS debugger in latest IntelliJ versions

### ISSUE THREAD

**Issue by antonio-madrid** [serenity-js/serenity-js#1520]
# Context

It seems the latest versions of IntelliJ are ignoring the use of the keyword `breakpoint` but not the keyword `debugger`.

As a result, the Serenity/JS debugger statement `Debug.setBreakpoint()` is not stopping the execution when running it in debug mode.

### Example code:
```TypeScript
When('{actor} logs in my site', async (actor: Actor) =>
   actor.attemptsTo(
           Debug.setBreakpoint(),
           Login.intoMySite.withCredentials(
               'random@gmail.com',
               '123456'
           ),
           Debug.setBreakpoint(),
           Navigate.to('https://www.wikipedia.org/'),
           Debug.setBreakpoint(),
       )
);
```

A workaround is implementing a custom Interaction which uses the `debugger` keyword instead.

```TypeScript
import { Interaction } from '@serenity-js/core';

export const SetABreakpoint = () =>
    Interaction.where(`#actor sets a breakpoint`, actor => {
        debugger;
    });
```

Similar issue: https://youtrack.jetbrains.com/issue/WEB-18160

**Comment by jan-molak** [comment]
I'm wondering if we shouldn't abandon the current experimental approach with the `debugger` statement altogether and instead rely on developers to set breakpoints directly in their IDE. Even if JetBrains again start to accept the `debugger` statement defined in a Serenity/JS Node module, there's no guarantee that it won't break in the future or that it won't break in other IDEs.

Thinking aloud, there are two main points when a developer might need to set a breakpoint to pause the execution of an actor workflow while the test is running:
- to inspect the system under test (e.g. use dev tools in their browser)
- to preview a resolved value of a `Question` at that point in the scenario

Since we can't rely on the IDE to honour the `debugger` statement defined in the framework code, any breakpoints should be set by the consumer code using whatever native tools the IDE provides.

I wonder if we could connect to an active debugging session and set breakpoints programmatically 🤔 

Notes to self:
https://github.com/CrabDude/babel-node-debug/blob/master/bin/bode-debug.js
https://nodejs.org/en/docs/guides/debugging-getting-started/
