### ISSUE TITLE
SerenityJS webdriverIO - Console reporter is displayed in a bunch only after the tests are completed

### ISSUE THREAD

**Issue by harivsudhang** [serenity-js/serenity-js#1521]
@jan-molak 
Hi Jan- Good Day ! Since the Protractor is getting deprecated, I have configured webdriverIO with Serenityjs V3 ("^3.0.0-rc.42"). Everything works fine except that, once all the tests are completed, only then the Console reporter starts streaming out with a bunch of results. 
Is there any configuration to display the console reporting to stream when the tests are executing? Thsi happens very well in Protractor. Let me know if you are unclear or need any further information.

**Comment by harivsudhang** [comment]
![image](https://user-images.githubusercontent.com/28986994/221775340-ef31f38b-089a-41f9-8245-0d59480c8ac0.png)

**Comment by jan-molak** [comment]
Hello @harivsudhang! WebdriverIO supports configuring multiple console reporters, so you could have say both `spec` and `@serenity-js/console-reporter`. 

To support this feature, WebdriverIO buffers the output of each reporter, including Serenity/JS Console Reporter, and prints it when the test run is finished. The advantage is that the different outputs don't overlap, the disadvantage is that you have to wait for the tests to finish to see the output.

It works the same way with Playwright Test for example, as they buffer the output of each worker and then print it out when they're finished.

Protractor could print the output straight away because it didn't support multiple reporters, or running tests in parallel (well, not without sharding).

Hope this helps!

**Comment by harivsudhang** [comment]
Thanks Jan
@manuelfidalgo 
Hi Manuel- Could you please guide me on this console reporting which you have done please?

**Comment by manuelfidalgo** [comment]
Hi @harivsudhang ,
Reportportal is about analytics on your test executions: it is a really valid tool to gather metrics about pass/fail rate, most flaky tests, etc.
While it shows what test is being executed, it does not show the steps (or I haven't configured it like that).
If you want to use it along with wdio, you need a [reportPortal instance](https://reportportal.io/docs/category/installation-steps/), [config file](https://github.com/reportportal/example-net-nunit/blob/master/src/Example/ReportPortal.config.json) and link that file in the reporters section of wdio, something like this:

 ```
 reporters: [
    'spec',

    [
      'junit',
      {
        outputDir: './target',
        outputFileFormat: function (options) {
          return `results-${options.cid}.xml`
        },
      },
    ],
    [reportPortalReporter, require('../reportportalConf')],
  ],
```

**Comment by harivsudhang** [comment]
@manuelfidalgo Thanks Manuel ! I will try it out
