### ISSUE TITLE
Serenity/JS 3.1.0 - Wait.for(Duration.ofSeconds(6)) fails with a TimeOutExpiredError after 5 seconds

### ISSUE THREAD

**Issue by viper3400** [serenity-js/serenity-js#1604]
Looks like there is a regression with the `Wait` implementation when using WebdriverIO (with Mocha).

I can reproduce this when I raise the timeout [here](https://github.com/serenity-js/serenity-js/blob/c440f1248f74c26dd9b6721a358bf19eb982458a/integration/web-specs/spec/screenplay/interactions/Wait.spec.ts#L55) from `2_500` ms to `6_000` ms.

From `./integration/webdriverio-web` run `npm run test`.

I would expect the test to continue and then pass after 6 seconds. Instead it fails before the set timeout, after 5 seconds with

```
[test:acceptance] [0-0] TimeoutExpiredError in "Wait for pauses the actor flow for the length of an explicitly-set duration"
[test:acceptance] TimeoutExpiredError: Timeout of 5s has expired
[test:acceptance]     at /workspace/serenity-js/packages/core/src/screenplay/time/models/Scheduler.ts:13:98
[test:acceptance] [0-0] FAILED in chrome - /node_modules/@integration/web-specs/spec/screenplay/interactions/Wait.spec.ts
```

Looks like setting an `interactionTimeout: Duration.ofSeconds(15)` in the `serenity`config of `wdio.conf.ts` has no effect, either. Test fails after 5 seconds with the `TimeOutExpiredError`.

**Comment by jan-molak** [comment]
Beautiful catch, @viper3400, I can reproduce it.

There are two issues here, actually.
The first one is that `WebdriverIOFrameworkAdapter` doesn't pass the `interactionTimeout` property to `Serenity.configure`. That's why increasing the timeout has no effect and you're still seeing 5 seconds instead of 15.

The second one seems to be an issue with `Wait.for(..)`. At the moment, if the timeout set with `Wait.for(..)` is longer than the max `interactionTimeout`, `Wait.for(..)` gets terminated when the `interactionTimeout` expires. On the one hand, this might be desired as you get to control all the max timeouts with `interactionTimeout`, but on the other hand, it feels unintuitive - if you tell the test to wait for 6 seconds, you'd expect it to wait for 6 seconds and perhaps not care much about the `interactionTimeout`
