### ISSUE TITLE
RFC - Remove TS files from @serenity-js artifacts

### ISSUE THREAD

**Issue by jan-molak** [serenity-js/serenity-js#1772]
At the moment all `@serenity-js` artifacts ship with:
- `.js` - JavaScript files 
- `.js.map` - JavaScript source maps
- `.d.ts` - TypeScript type definitions
- `.d.ts.map` - TypeScript source maps
- `.ts` - actual TypeScript sources

We could remove `.d.ts.map` and `.ts` files to reduce the size of the artifacts.

Outstanding questions:
- is there any scenario where having `.d.ts.map` and `.ts` shipped with the artifacts is useful?
- if we remove `.d.ts.map` and `.ts` files, how would this affect the stack traces of errors thrown internally in Serenity/JS?

**Comment by viper3400** [comment]
Hi @jan-molak, why distribution size got your attention? Is there any urgent need to reduce the size?

To be honest, I'm not aware of the current size of the packages. But as we depend (indirectly) on binaries like the bdd reporter, chromedriver, playwright etc., I assume the size of this dependencies is bigger than the amount we would save by removing this parts.

And you name it: You would remove some valuable stack trace informations and probably some IDE suppport. Won't the removal of the map files remove some IDE support as well?

**Comment by jan-molak** [comment]
> why distribution size got your attention?

OK, so it's going to be a fairly long answer. Sorry about that 😊 

I started investigating upgrading Lerna to v7, but since it introduces a [number of backwards-incompatible changes](https://github.com/lerna/lerna/blob/main/CHANGELOG.md#breaking-changes), I'm coming to a conclusion that perhaps it makes more sense to move straight to Nx.js instead. Nx is what [runs under Lerna's hood](https://lerna.js.org/docs/lerna-and-nx) anyway.

I've been experimenting with Nx over the last few days and really like its speed and the development workflow it offers. I think that with a few tweaks, it could work for us too.

Now, in my experiments with Nx I noticed that when it uses its default/recommended settings to build a TypeScript library it leaves only the `.js`, `.js.map` and `.d.ts` files in the artifact. Sources used to _produce_ the resulting JavaScript, so `.ts`, are not included. I think it makes sense since no one really imports the `.ts` files themselves from a library. Plus, the original sources can only really be used to quickly study the framework code in the comfort of your IDE, or debug the library code itself - which, in theory, most people don't do.

I haven't really ever considered _not_ bundling the `.ts` files with the artifacts, it just _felt_ like the right thing to do. This realisation struck me as not a very "_engineering_" thing to do, so I did some more research.

I decided to look at other Node projects written in TypeScript, and to my surprise - _none_ of the popular modules like WebdriverIO, Playwright, Axios, to name but a few, bundled their `.ts` sources.

So this thread is really a reminder to check what value people are getting from the bundled `.ts` files, and if it's useful to carry on shipping Serenity/JS modules with both the transpiled and original sources.

**Comment by viper3400** [comment]
Okay, two different things here?
- How others do (and why)?
- Consequences for Serenity/JS?

I also want to differentiate between different views when debugging "Serenity/JS" and different forms of "developer experience":
* The pure tester view who suspects an error either in the application under test or in the way the test specs or locators are written to produce an unwanted result. They do suspect an error on their site and not a bug in Serenity/JS
* The pure developer view who ensured correct function of the application under test and ensured that specs, locators etc. are correct.  Now they suspect a bug in Serentiy/JS and try to debug.
* The contributor view. They are just eager to understand what happens in Serenity/JS when they do this or that in order to contribute.

To be honest, today was the first time I even managed to setup a VS Code `launch.json` to debug directly into the Serenity/JS TS code from a consuming test project. Until now I just looked into the filename & line numbers in the stack trace when I tried to "debug" Serenity/JS.

When "debugging" from a tester view, there may be other approaches than to dive deep into the Serenity/JS code, at all. 

Btw. what would be the consequence in the monorepo? Would you still be able to simple debug within there?

Finally, is it "_unengineering_" to do things not like the others? Aren't most projects rooted in pure JS and just _used_ only to ship the js files? Don't kow, would have to ask :)

For me the question is, what to loose, what to gain?

**Comment by jan-molak** [comment]
> Btw. what would be the consequence in the monorepo? Would you still be able to simple debug within there?

Ha, now that's a very good point :D I'll add it to my list of things to check.

> Finally, is it "unengineering" to do things not like the others? 

Haha, not at all, there is plenty of things that Serenity/JS does differently than the others and that's perfectly fine :-)

> For me the question is, what to loose, what to gain?

Yes, that's exactly what I'm trying to figure out. I wonder if it's possible to keep the debugging capabilities and informative stack traces while reducing the number of files in an artifact. It's perfectly possible that the answer here is "no", in which case I'd definitely favour debugging over artifact size.

**Comment by jan-molak** [comment]
Closing as I'm no longer convinced this is a useful thing to do.
