### ISSUE TITLE
Chrome ENOENT error on template repository serenity-js cucumber-webdriverio  

### ISSUE THREAD

**Issue by pawelmisiura** [serenity-js/serenity-js#1841]
### What happened?

I am seeing the following error when running `npm test` on the 'serenity-js-cucumber-webdriverio-template' repository

Using node 16.14.2

`
[test:execute] [0-0] RUNNING in chrome - file:///features/authentication/form_authentication.feature

[test:execute] [0-0] Error: spawn /var/folders/z3/lcs1yxmx7tl_lz1x8frb1cr80000gq/T/chromedriver/mac_arm-115.0.5790.170/chromedriver-mac-arm64/chromedriver ENOENT

[test:execute] [0-0]     at Process.ChildProcess._handle.onexit (node:internal/child_process:283:19)

[test:execute] [0-0]     at onErrorNT (node:internal/child_process:478:16)

[test:execute] [0-0]     at processTicksAndRejections (node:internal/process/task_queues:83:21) {

[test:execute] [0-0]   errno: -2,

[test:execute] [0-0]   code: 'ENOENT',

[test:execute] [0-0]   syscall: 'spawn /var/folders/z3/lcs1yxmx7tl_lz1x8frb1cr80000gq/T/chromedriver/mac_arm-115.0.5790.170/chromedriver-mac-arm64/chromedriver',

[test:execute] [0-0]   path: '/var/folders/z3/lcs1yxmx7tl_lz1x8frb1cr80000gq/T/chromedriver/mac_arm-115.0.5790.170/chromedriver-mac-arm64/chromedriver',

[test:execute] [0-0]   spawnargs: [ '--port=61190', '--allowed-origins=*', '--allowed-ips=' ]

[test:execute] [0-0] }

[test:execute] [0-0] FAILED in chrome - file:///features/authentication/form_authentication.feature
`

### What did you expect to happen?

I expect the example test to run successfully. 

### Serenity/JS version

```shell
"dependencies": {
    "@cucumber/cucumber": "^9.3.0",
    "@serenity-js/assertions": "^3.9.0",
    "@serenity-js/console-reporter": "^3.9.0",
    "@serenity-js/core": "^3.9.0",
    "@serenity-js/cucumber": "^3.9.0",
    "@serenity-js/serenity-bdd": "^3.9.0",
    "@serenity-js/web": "^3.9.0",
    "@serenity-js/webdriverio": "^3.9.0",
    "@wdio/cli": "^8.14.4",
    "@wdio/globals": "^8.14.3",
    "@wdio/local-runner": "^8.14.3",
    "@wdio/spec-reporter": "^8.14.0",
    "webdriverio": "^8.14.3"
  },
  "devDependencies": {
    "@typescript-eslint/eslint-plugin": "^6.2.1",
    "@typescript-eslint/parser": "^6.2.1",
    "eslint": "^8.46.0",
    "eslint-plugin-import": "^2.28.0",
    "eslint-plugin-simple-import-sort": "^10.0.0",
    "eslint-plugin-unicorn": "^48.0.1",
    "eslint-plugin-unused-imports": "^3.0.0",
    "http-server": "^14.1.1",
    "mkdirp": "^3.0.1",
    "npm-failsafe": "^1.0.0",
    "rimraf": "^5.0.1",
    "ts-node": "^10.9.1",
    "typescript": "^5.1.6"
  }
```

### Node.js version

16.14.2

### Execution environment

Mac OS, chrome. 

### How to reproduce the bug.

Clone the following repository: https://github.com/serenity-js/serenity-js-cucumber-webdriverio-template.git run `npm intall` then `npm test`

**Comment by jan-molak** [comment]
Hi @pawelmisiura! It looks like an issue with WebdriverIO browser downloader, similar to webdriverio/webdriverio#10861

I tried to reproduce it, but it seems like downloading works, and all the tests pass:
- on [GitHub Actions](https://github.com/serenity-js/serenity-js-cucumber-webdriverio-template/actions) using Ubuntu Linux 22.04
- on [GitPod](https://github.com/serenity-js/serenity-js-cucumber-webdriverio-template#usage)
- on my local Mac running Node 16.14.2 and 16.20.0.

So I wonder if the issue is specific to your local setup or network connectivity 🤔 
What version of macOS are you using? I'm on Ventura 13.4.1 (c)

Could you please also check if one of the following resolves the issue:
- setting [`maxInstances: 1`](https://github.com/serenity-js/serenity-js-cucumber-webdriverio-template/blob/e793dc05f12cee610ad45d0c126b984513eec7c9/wdio.conf.ts#L68) as per the webdriverio/webdriverio#10861
- using [WebdriverIO Chromedriver service](https://webdriver.io/docs/wdio-chromedriver-service/) instead of [`capabilities.browserVersion: 'stable'`](https://github.com/serenity-js/serenity-js-cucumber-webdriverio-template/blob/e793dc05f12cee610ad45d0c126b984513eec7c9/wdio.conf.ts#L84) (so reverting https://github.com/serenity-js/serenity-js-cucumber-webdriverio-template/commit/42a69cb4015bbdaf3f61b740103254de152ed6a3 in `wdio.conf.ts`)

**Comment by jan-molak** [comment]
Hi @pawelmisiura! I haven't heard back from you in a month so I'm assuming that it was a temporary glitch you've managed to resolve. I'll close this ticket, but please let me know should you come across any issues with Serenity/JS in the future.
