### ISSUE TITLE
Need help in running playwright serenity js example

### ISSUE THREAD

**Issue by AnnneN** [serenity-js/serenity-js#1877]
Hi team,
I Need help in running playwright serenity js example, i used below template and used npm test but when i checked index.html, nothing is appearing.

https://github.com/serenity-js/serenity-js-cucumber-playwright-template#readme
@jan-molak

**Comment by jan-molak** [comment]
Hi @AnnneN! It's challenging to help you without seeing what you see.

[Serenity/JS Cucumber Playwright Template](https://github.com/serenity-js/serenity-js-cucumber-playwright-template) is configured to run the tests and publish test reports to GitHub Pages, and those seem to be [produced correctly](https://serenity-js.github.io/serenity-js-cucumber-playwright-template/). I can't reproduce the issue locally either, I'm afraid.

If you believe there's a bug in the template or Serenity/JS itself, I'd be grateful if you could follow the [bug reporting guide](https://serenity-js.org/contributing/#report-an-issue) and share:
- the details of your execution environment, so the operating system and version of Node JS
- printout of `npm ls --all` so that we can see if there are any issues with your Serenity/JS installation
- log output produced by the test run

And anything that you think could help us reproduce the issue. Thanks!

**Comment by AnnneN** [comment]
Thank you for reply but let me explain again.
I downloaded the above template and ran below command
npm ci( success) 
and now I run npm test
now the issue is I dont see any out put, I also checked in folder 'target/site/serenity' but no tests there.

**Comment by jan-molak** [comment]
Sure, but since the template seems to work correctly on CI and other machines, I suspect some issues with the local setup. To verify that, we need to know the difference between your setup and the ones that work, hence my questions above.

**Comment by AnnneN** [comment]
node version is 17.6.0

**Comment by jan-molak** [comment]
OK, so as you can see in the [Serenity/JS installation guide](https://serenity-js.org/handbook/about/installation/#installing-nodejs), Serenity/JS supports only Long-Term Support versions of Node.js.

Node 17 is not an LTS but a dev version of Node.js, so I'd suggest to start with upgrading to Node 18 which is the current LTS.

**Comment by AnnneN** [comment]
Thanks, I was able to run after node upgrade.

**Comment by jan-molak** [comment]
Great, thanks for confirming! Enjoy Serenity :-)

**Comment by AnnneN** [comment]
Another question, why arent we using playwright.config file here. 
What can I do if  want to use it..also I want to mention which features needs to be run.
How can I do so? Pls guide.

**Comment by AnnneN** [comment]
@jan-molak  pls look into my query
