### ISSUE TITLE
Serenity + Karma

### ISSUE THREAD

**Issue by lwouis** [serenity-js/serenity-js#218]
I opened a [similar issue](https://github.com/cucumber/cucumber-js/issues/1095) on the Cucumber repo. My goal would be to run Cucumber tests using Karma. There seems to be no active project doing this at the moment.

Since Serenity provides an alternative to [protractor-cucumber-framework](https://github.com/protractor-cucumber-framework/protractor-cucumber-framework), I was wondering if you had plans to support an adapter to Karma as well.

Integration with protractor works great, but protractor is really e2e and slow. I would like to be able to have fast tests using cucumber, that I can run in watch mode while I work. This would be a great promotion tool for testing. Protractor tests are way too slow to use as a watch mode tool.

**Comment by jan-molak** [comment]
Hi there and thanks for the idea! I'm working on making it easier for people to integrate Serenity/JS with other test runners. I'm currently focusing on Jest (#164), so hopefully this work could support other integrations, such as Karma.

**Comment by jan-molak** [comment]
It doesn't yet, but I'll consider that for Serenity/JS v2!

**Comment by jan-molak** [comment]
OK, so my quick research shows that this might involve a considerable amount of work - my current understanding is that Serenity/JS would need to run in the browser and simulate events like `click` or `sendKeys` and communicate with the test runner, which would generate the report.
I do like the idea of running tests this way, but I'll get Serenity/JS v2 out of the way first and then look into this one.

**Comment by jan-molak** [comment]
Hi all, I wonder, is the use case for Karma different to the one for Cypress #326?

**Comment by casparov-pablo** [comment]
> Hi all, I wonder, is the use case for Karma different to the one for Cypress #326?

Hi @jan-molak  not sure it's the right place for this comment but, since you are now on investigating the Cyrpress and Karma things, maybe that's the good point to take Puppeteer into consideration as well? I mean there is #487  issue which points to protractor being abandoned, and for the sake of Serenity-Js evolution it will be great to expose some Interfaces to implement adapters easier for other browser manipulation tools. Nowadays tools like Cypress and Puppeteer seems to kick of the selenium out of the market and from my point of view Serenity-Js can facilitate from having those supported. 
I've just started investigating how can I bring the Puppeteer to Serenity-Js, but still there are a lot of questions to be raised and addressed. If there are any docs or guidelines, could you please share?

**Comment by jan-molak** [comment]
Hi @pavel-casparov - Serenity/JS v2 is modular by design and can be extended to support other browser integration tools. Let's move this conversation to #493
