### ISSUE TITLE
Is there an example that does NOT use protractor?

### ISSUE THREAD

**Issue by pscanlon1** [serenity-js/serenity-js#247]
Im having trouble setting up a simple test scenario with mocha and serenity.. I have a websocket library of API calls, not REST, that I will use inside tasks...

Maybe im just missing it but all the examples seem to use protractor?

**Comment by jan-molak** [comment]
Hi @pscanlon1 and welcome to the Serenity/JS community :-)

You're right, Web UI testing is probably the most common use case for Serenity/JS, but the library is modular and can be easily extended to support testing other interfaces of your system.

For example, here's a [demo test suite](https://github.com/serenity-js/tutorial-bdd-trader) that interacts with a REST endpoint using `@serenity-js/rest` (without `protractor`).

If you'd like to interact with a websocket instead you'd need a mechanism similar to the one above:
- an `Ability` class that wraps a websocket client, so that the `Actor` can use it; similar to [`CallAnApi`](https://github.com/jan-molak/serenity-js/blob/14c589668d08bf38c41c93234482a779c0af4377/packages/rest/src/screenplay/abilities/call_an_api.ts)
- some `Interaction`s that make use of that `Ability`, so that they can form a foundation for other higher-level `Tasks`; similar to [`Get`](https://github.com/jan-molak/serenity-js/blob/master/packages/rest/src/screenplay/interactions/get.ts), [`Post`](https://github.com/jan-molak/serenity-js/blob/master/packages/rest/src/screenplay/interactions/post.ts), etc.

I hope this helps, but please let me know if you have any further questions!
Jan

**Comment by pscanlon1** [comment]
Ok this is a good start... 

2 questions on this.

My  SDK is a collection of methods, that in turn use a websocket, so im not sure that i need to do much  besides implement the "as" and "using" functions within the ability..

right now i would do something like

const api = new Api('some/ws/url')
api.callSomeMethod(param1)

Obviously I do not want to add each method from my API, so I guess that in my Tasks, I would create things that do a Login, callSomeMethod() ?
Hope this makes sense..

2. Im having trouble just running it outside of the protractor context... How are you running the above demo test suite?  Just serenity run ?

**Comment by pscanlon1** [comment]
When I run the above demo... I end up getting the error below:

```
[report] Error: WARNING: An illegal reflective access operation has occurred
[report]     at /Users//Documents/tutorial-bdd-trader/node_modules/serenity-cli/lib/actions/logging.js:9:35
[report]     at <anonymous>
[report]     at process._tickCallback (internal/process/next_tick.js:188:7)
[report] npm ERR! code ELIFECYCLE
[report] npm ERR! errno 1
[report] npm ERR! bdd-trader@1.0.0 report: `serenity run`
[report] npm ERR! Exit status 1
[report] npm ERR!
[report] npm ERR! Failed at the bdd-trader@1.0.0 report script.
[report] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[report]
[report] npm ERR! A complete log of this run can be found in:
[report] npm ERR!     /Users//.npm/_logs/2018-07-20T15_28_13_243Z-debug.log
[failsafe] Script 'report' exited with code 1
npm ERR! Test failed.  See above for more details.
```

**Comment by pscanlon1** [comment]
Thanks Jan yes it helps... Im still getting the above error when i run the demo project. Could it be my java version?

$ java --version
java 9.0.1

**Comment by jan-molak** [comment]
Possibly, I'd suggest using Java 8

**Comment by jan-molak** [comment]
Hey @pscanlon1 - I haven't heard from you in a while, so I assume that this ticket can be closed. Please feel free to re-open it or raise a new one if you'd like any further assistance.
