### ISSUE TITLE
Check evaluation issue

### ISSUE THREAD

**Issue by san-ouadghiri** [serenity-js/serenity-js#255]
Hi,

So I've been using check lately and I encounter an issue.

This works
```
it('Choose the "all" element ', () => guy.attemptsTo(
            ChooseElement.set("all")
        ));
```
+
```
set: (elemnt: string): Task => Task.where(`#actor choose the ${element} element`,
        Check.whether (element == 'all')
            .andIfSo(
                Wait.until(Elements.all(), Is.visible()),
                Scroll.to(Elements.all()),
                Click.on(Elements.all())
            ).otherwise (
                //Nothing
            )
```

But this doesn't, if in otherwise I put lines that do not works for "all" ( ex Scroll.to(Elements.locator(element)), where Elements.locator("all") is not defined).

` Choose the "all" Element :
[all:chrome]      TypeError: Cannot read property 'label' of undefined (locator calls something.labels which is indeed indefined for "all")
[all:chrome]       at Object.locator (src/screenplay/interactions/user_interface/elements.ts:7:112)
[...]
[all:chrome]       at runTest (node_modules/serenity-js/src/serenity-mocha/controlflow.ts:96:32)
[...]
`

The whole purpose of my check usage here is to deal differently if the string is "all" or not "all". So having an error because it can't evaluate anything within "otherwise" for this string value is problematic to me.

In my opinion, andIfSo & Otherwise should only be evaluated when the condition is met, and tasks within it should not interfere with one another. But maybe that's not how it works ?

Did I miss a mistake I made/can I do what I want to do differently, or is it indeed something to fix at the library level ? Have a good day, and thanks again for your work :) !

San.

**Comment by nbarrett** [comment]
Hi @san-ouadghiri - I think there are two considerations with regard to your problem:

- if you include .otherwise() you must provide valid `Activity...` values otherwise undefined will be returned which will cause downstream runtime errors.
- if you do provide  `Interaction` or `Task` values for `.andIfSo()` or `.otherwise()` they will always BOTH  be evaluated into Activity instances regardless of the value of Check.whether(). It's important to remember that the `Check()` conditional only affects the execution (e.g. the invocation of the `performAs()` method(s) and not the construction of the actual tasks. 

The second point  is actually a very easy to forget aspect of serenity programming!  If you want to avoid evaluating arguments in a conditional argument, wrap them in a higher level `Activity`, then only the 'outer' level will be instantiated at runtime.

**Comment by san-ouadghiri** [comment]
Hi @nbarret,

Yep, your 2nd point is my "issue". The part I omitted. So I'm interested in your suggrstion. So i could wrap them into an activity for it to be evaluated at run time... but i still need a boolean for my check. Could you give me an example of what you thought about, just to make it more explicite ?

**Comment by jan-molak** [comment]
Hi @san-ouadghiri - the interaction to [`Check`](https://serenity-js.org/modules/assertions/class/src/Check.ts~Check.html) has been completely re-written in Serenity/JS 2.0. Please check out the [API docs](https://serenity-js.org/modules/assertions/class/src/Check.ts~Check.html) and [unit tests](https://serenity-js.org/modules/assertions/test-file/spec/Check.spec.ts.html) that demonstrate usage examples.

Hope this helps!
Jan
