### ISSUE TITLE
State of 2.0?

### ISSUE THREAD

**Issue by ctaepper** [serenity-js/serenity-js#318]
Hi Jan, I'm a big fan of your work ever since we started using serenity-js over a year ago. 

First of all, sorry for opening an issue here, but I don't know how else I can get in touch with you...

I'm with a new company starting a new project and I definitely want to use serenity for our e2e needs. I can see v2 is under heavy development and you do regular alpha releases. Now I am wondering if it still makes sense using the current serenity version when starting a new project, meaning will v2 be an "easy" upgrade path or is it a larger rewrite and we should wait for v2 being released and even more important: documented

**Comment by jan-molak** [comment]
Hi @ctaepper! Thanks for your kind words and your support for Serenity/JS :-)

I'm finishing the last major feature for v2 now, which is adding support for the Jasmine framework. After that, the last thing that's left is to update the handbook and the tutorials - I think we're looking at a release date at some point in June.

Most classes already have comprehensive JSDoc with usage examples and those that don't will get it over the coming weeks, there are also several [example mini-project](https://github.com/jan-molak/serenity-js/tree/2.0/examples) that demonstrate the major features.

I've designed v2 so that the upgrade path _should be_ relatively straight-forward as the main classes (`Actor`, `Task`, `Interaction` and `Question`) are backwards compatible.

Having said that, if you're starting a new project now I'd suggest to either go with the `alpha`, which is now stable and any changes are limited to the internals, or wait for the "official release".

What I can also propose is that if you (or others) would like to experiment with v2 you could use this ticket to ask any questions about the new version or let me know if there are things we should address before the official realease.

**Comment by asnov** [comment]
@jan-molak,
I tried to migrate some of my old tests to v2 and I didn't find photographer stage crew. What happened to him?
What can I use instead?

**Comment by jan-molak** [comment]
@asnov - Since [`Photographer`](https://github.com/jan-molak/serenity-js/blob/2.0/packages/protractor/src/stage/index.ts) is Protractor-specific, he decided to move to the `@serenity-js/protractor` module ([specs available here](https://github.com/jan-molak/serenity-js/blob/2.0/packages/protractor/spec/stage/photographer/Photographer.spec.ts#L36)).

```typescript
import { Photographer, TakePhotosOfFailures } from '@serenity-js/protractor';

new Photographer(new TakePhotosOfFailures())
```

- [ ] Which reminds me that I should add a factory method to make the instantiation simpler, maybe something like `Photographer.who(TakesPhotosOfFailures)` 🤔

**Comment by owlran** [comment]
hi @jan-molak,

is any v2 document available ?

**Comment by jan-molak** [comment]
Hi @owlran - the website hasn't been published yet as it would replace the existing one for version 1.
If you'd like to see a preview of the website for v2 you can clone this repository, checkout the `2.0` branch and run `make clean site` which generates the website under `documentation/website/target`.

**Comment by Ijee** [comment]
Hey,
I tried updating one of my projects to the new version but I am running into a few issues which you might be able to help me with:

-  I can not find the `Is` class - do I have to implement that myself using protractor or is it somewhere else?
- I can not find the  TakeNotes ability. Do you plan on adding it back?
- @step('') for performAs for my custom tasks is not available anymore? It doesn't say anything about removing it in the changelog.

**Comment by jan-molak** [comment]
Hi @Ijee!

> I can not find the Is class - do I have to implement that myself using protractor or is it somewhere else?

The `Is` class from 1.x has now been replaced with [expectations](https://github.com/jan-molak/serenity-js/tree/2.0/packages/protractor/src/expectations) that can be used with both `Wait` and `Ensure`. For example:

```typescript
import { isClickable, Wait } from '@serenity-js/protractor';
import { Ensure } from '@serenity-js/core';

actor.attemptsTo(
  Wait.until(Form.Submit_Button, isClickable()),
  // but also:
  Ensure.that(Form.Submit_Button, isClickable()),
);
```

> I can not find the TakeNotes ability. Do you plan on adding it back?

Yes, it will be added back in some form. If you need it right now you could copy the one from 1.x ([source](https://github.com/jan-molak/serenity-js/blob/master/packages/core/src/screenplay/abilities/take_notes.ts))

> @step('') for performAs for my custom tasks is not available anymore? It doesn't say anything about removing it in the changelog.

In 1.x the `@step` annotation would emit events when the activity was started/finished. In 2.x this responsibility is now with the `Actor` who uses the description of an activity provided by its `toString()` method. This means that the only thing that the `@step` would do in 2.x would be to generate a `toString()`... which doesn't seem that useful.

In other words, instead of:

```typescript
export class DoSomethingCool extends Interaction {

  @step('#actor does something cool')
  performAs(actor: UsesAbilities & AnswersQuestions): PromiseLike<void> {
       return SomeAbility.of(actor).doStuff();
  }
}
```

you can simply:
```typescript
export class DoSomethingCool extends Interaction {

  performAs(actor: UsesAbilities & AnswersQuestions): PromiseLike<void> {
       return SomeAbility.of(actor).doStuff();
  }

  toString() {
      return '#actor does something cool';
  }
}
```
or even shorter:
```typescript
import { Interaction } from '@serenity-js/core';

export DoSomethingCool = () =>
    Interaction.where(`#actor does something cool`, actor =>
        SomeAbility.of(actor).doStuff());
```

> I also found that Check.whether(condition: boolean | Question<boolean> | Question<PromiseLike<boolean>>) {...} got changed to
Check.whether<A>(actual: Answerable<A>, expectation: Expectation<any, A>) {...}.
I tried changing it using this new Ensure thing but it did not work. Do you have an example for it? 

You're correct. An `Answerable` is either a `Question<Promise<value>>`, a `Question<value>`, a `Promise<value>` or just a `value`.

This means that you could do things like:

```typescript
Check.whether(process.env.BASE_URL, includes('dev'))
    .andIfSo(
        DoOneThing(),
    )
    .otherwise(
        DoSomeOtherThing(),
    )
```

But also:

```typescript
Check.whether(Cookies.Consent_Form, isVisible())
    .andIfSo(
        Click.on(Cookies.Accept)
    )
```

You can find some examples in the [specs](https://github.com/jan-molak/serenity-js/blob/2.0/packages/assertions/spec/Check.spec.ts)

> (I am probably just stupid atm)

I'm sure that's not the case :-)

Thanks for taking the time to try 2.x and report the issues! If you come across anything else, please let me know!

**Comment by jan-molak** [comment]
@Ijee I've just added `TakeNotes` back in, here's an example of how you'd use it:

```typescript
import { Note, TakeNote, TakeNotes } from '@serenity-js/core'
import { BrowseTheWeb, Target, Text } from '@serenity-js/protractor'
import { by, protractor } from 'protractor';

const VoucherCode = () => Target.the('voucher code').located(by.id('voucher'));
const AppliedVoucherCode = () => Target.the('voucher code').located(by.id('applied-voucher'));

const actor = Actor.named('Noah').whoCan(
    TakeNotes.usingAnEmptyNotepad(),
    BrowseTheWeb.using(protractor.browser),
);

actor.attemptsTo(
    TakeNote.of(Text.of(VoucherCode())),
    // ... add the product to a basket, go to checkout, etc.
    Ensure.that(AppliedVoucherCode(), equals(VoucherCode())),
);
```

The cool thing about `Note.of` is that you can use it with assertions:
```typescript
Ensure.that(Note.of(AppliedVoucherCode()), equals('SUMMERSALE'))
```
or interactions:
```typescript
Enter.theValue(Note.of(VoucherCode())).into(Checkout.VoucherCodeField);
```

Hope this helps!

**Comment by nbarrett** [comment]
Noted - cheers! 👍

**Comment by abhinaba1080** [comment]
Hi @jan-molak : any update on release dates of serenity-ks 2.0 officially?

**Comment by jan-molak** [comment]
@abhinaba1080 - I decided to fix some bugs in Serenity/JS CLI before the release, which ended up becoming a re-write of the CLI... I'm almost finished with that though, so the last bit is the tutorials and more documentation. Thanks for your patience!

**Comment by abhinaba1080** [comment]
> @asnov - Since [`Photographer`](https://github.com/jan-molak/serenity-js/blob/2.0/packages/protractor/src/stage/index.ts) is Protractor-specific, he decided to move to the `@serenity-js/protractor` module ([specs available here](https://github.com/jan-molak/serenity-js/blob/2.0/packages/protractor/spec/stage/photographer/Photographer.spec.ts#L36)).
> 
> ```ts
> import { Photographer, TakePhotosOfFailures } from '@serenity-js/protractor';
> 
> new Photographer(new TakePhotosOfFailures())
> ```
> 
> Which reminds me that I should:
> 
> * [ ]  add a factory method to make the instantiation simpler, maybe something like `Photographer.who(TakesPhotosOfFailures)` 🤔
> * [ ]  document that the `Photographer` has moved elsewhere. Maybe a migration guide could be useful?

@asnov  does the Photographer working for you? Its not for me eventually. Can you share your serenity version and piece of configuration? 

@jan-molak : i am really stuck, kindly look into this:  https://github.com/jan-molak/serenity-js/issues/335

**Comment by jan-molak** [comment]
@abhinaba1080 - I've replied in #335, so let's move this conversation there, please.

**Comment by jan-molak** [comment]
All, I've moved the `SerenityBDDReporter` class to a dedicated module `@serenity-js/serenity-bdd` responsible for integrating Serenity/JS with Serenity BDD reporting CLI.

Additionally, the `@serenity-js/serenity-bdd` module ships with a brand new CLI wrapper, which you can use to download the Serenity BDD jar:

```
serenity-bdd update
```

and generate the reports:
```
serenity-bdd run
```

This means that you no longer need to use the old `serenity-cli` module and can switch to the new one at your convenience.

A more in-depth description of the new module can be found in its [readme](https://github.com/jan-molak/serenity-js/tree/2.0/packages/serenity-bdd).

The new implementation has an improved downloader, which can restart the download should it be interrupted, as well as a better Java detection mechanism, so you should no longer see warnings on Linux-based systems.

Fun fact: the new CLI wrapper is [written in Serenity/JS Screenplay](https://github.com/jan-molak/serenity-js/tree/2.0/packages/serenity-bdd/src/cli) ;-)

**Comment by dguerrier** [comment]
When will the 2.0 alpha release be available as an npm package?

**Comment by jan-molak** [comment]
Hi all,

I've just put together a small template project demonstrating the setup required to run tests using Serenity/JS v2 (alpha), Cucumber v5 and Protractor - https://github.com/serenity-js/serenity-js-cucumber-protractor-template

Thoughts and feedback welcome.

**Comment by ctaepper** [comment]
@jan-molak would you shed some light on[ this topic](https://github.com/jan-molak/serenity-js/issues/132) in 2.0? When I run tests using browserstack and multicapabilities I do not see any tagging of browsernames in the tests. Is this feature still pending in 2.0?

**Comment by jan-molak** [comment]
Hi all,

I've just published a new [`@serenity-js/console-reporter`](https://www.npmjs.com/package/@serenity-js/console-reporter) module that supersedes the experimental (and now deleted!) `ConsoleReporter` class that used to ship with `@serenity-js/core`.

Have a look at the module's readme for full [installation instructions](https://github.com/jan-molak/serenity-js/tree/2.0/packages/console-reporter).

To upgrade from the experimental `ConsoleReporter` to the new version, please install the new module:

```console
npm install --save @serenity-js/console-reporter
```

and update your Protractor config:

```diff
// protractor.conf.js

- const { ConsoleReporter } = require('@serenity-js/core');
+ const { ConsoleReporter } = require('@serenity-js/console-reporter');

exports.config = {
  framework:      'custom',
    frameworkPath: require.resolve('@serenity-js/protractor/adapter'),
    serenity: {
      crew: [
-       new ConsoleReporter(),
+       ConsoleReporter.withDefaultColourSupport(),
      ],
      // other Serenity/JS config
    },
    // other Protractor config
 };
```

Please note that the new `ConsoleReporter` supports several colour themes, which you can choose by calling either of the following factory methods:

```typescript
ConsoleReporter.withDefaultColourSupport()
ConsoleReporter.forMonochromaticTerminals()
ConsoleReporter.forDarkTerminals()
ConsoleReporter.forLightTerminals()
```

All the [existing implementation examples](https://github.com/jan-molak/serenity-js/tree/2.0/examples) have also been updated to use the new `ConsoleReporter`.

And here are some screenshots:
![image](https://user-images.githubusercontent.com/1089173/69505621-bcdb1300-0f22-11ea-9b95-fbfc91f95bc1.png)

![image](https://user-images.githubusercontent.com/1089173/69505634-cb292f00-0f22-11ea-9696-52c62dcee4d5.png)


Thoughts and feedback welcome!

**Comment by abhinaba1080** [comment]
This feature is killing.. But still it is alpha :stuck_out_tongue_closed_eyes:

Can't wait for the official release..

**Comment by jan-molak** [comment]
> Can't wait for the official release..

Working on it 👨‍💻

**Comment by KyleFairns** [comment]
@jan-molak I feel like the indentation is different when working with cucumber (in alpha-89, at the least), but the existing extra feedback from execution is definitely helpful.

You have the step, a single indentation, and then the serenity steps in a list, not indenting further when a new interaction is introduced (which may be intended, because it reduces noise), but it may be nice to have an option to be able to include some more noise with the interaction descriptions so the intent is clearer in the output, or to remove the description of the interactions (like "Wendy attempts to log in (4s 808ms)" in the examples below) in order to avoid confusion.

Current (based on the Mac Terminal, another terminal called Hyper [powered by electron] and also the Jetbrain's Webstorm terminal):

```
Given Wendy is using us as her supplier
    ✓ Wendy enables synchronisation with Angular (0ms)
    ✓ Wendy navigates to '/login' (1s 944ms)
    ✓ Wendy visits the login page (1s 945ms)
    ✓ Wendy waits up to 5s until the email field does become visible (146ms)
    ✓ Wendy enters 'yeahthisemailisfake@wendysemailprovider.com' into the email field (112ms)
    ✓ Wendy enters 'password' into the password field (47ms)
    ✓ Wendy clicks on the login button (48ms)
    ✓ Wendy waits for 2s 500ms (2s 505ms)
    ✓ Wendy attempts to log in (4s 808ms)
```

Expected (following the same pattern as shown in your previous screenshots): 

```
Given Wendy is using us as her supplier
    Wendy attempts to log in
        ✓ Wendy enables synchronisation with Angular (0ms)
        ✓ Wendy navigates to '/login' (1s 944ms)
        ✓ Wendy visits the login page (1s 945ms)
        ✓ Wendy waits up to 5s until the email field does become visible (146ms)
        ✓ Wendy enters 'yeahthisemailisfake@wendysemailprovider.com' into the email field (112ms)
        ✓ Wendy enters 'password' into the password field (47ms)
        ✓ Wendy clicks on the login button (48ms)
        ✓ Wendy waits for 2s 500ms (2s 505ms)
    ✓ Wendy attempts to log in (4s 808ms)
```

Are you already aware of this, or should I create a ticket?

**Comment by jan-molak** [comment]
Hey @KyleFairns and thanks for your feedback! 

The formatting reflects the structure of the tasks your actor performs.

The output in your example would've been produced in a scenario similar to the one below:

```typescript
actor.attemptsTo(
  UseAngular.enableSynchronisation(),
  Navigate.to('/login'),
  Wait.until(emailField, isVisible()),
  Enter.theValue('yeahthisemailisfake@wendysemailprovider.com').into(emailField),
  Enter.theValue('password').into(passwordField),
  Click.on(loginButton),
)
```

If you introduced domain-specific tasks, for example:

```typescript
const LaunchTheApp = () => 
  Task.where(`#actor launches the app`, 
    UseAngular.enableSynchronisation(),
    Navigate.to('/login'),
  );

const Authenticate = {
  using: (email: string, password: string) => 
    Task.where(`#actor authenticates using '${ username }' and password '${ password }'`,
        Wait.until(emailField, isVisible()),
        Enter.theValue(username).into(emailField),
        Enter.theValue(password).into(passwordField),
        Click.on(loginButton),
    ),
}
```

And used the following flow instead:
```typescript
actor.attemptsTo(
  LaunchTheApp(),
  Authenticate.using('yeahthisemailisfake@wendysemailprovider.com', 'password'),
)
```

You'd see that the level of indentation reflects how deeply the tasks are nested.

```console
Given Wendy is using us as her supplier
  Wendy Launches the app
    ✓ Wendy enables synchronisation with Angular (0ms)
    ✓ Wendy navigates to '/login' (1s 944ms)
  Wendy authenticates using 'yeahthisemailisfake@wendysemailprovider.com' and password 'password'       
    ✓ Wendy waits up to 5s until the email field does become visible (146ms)
    ✓ Wendy enters 'yeahthisemailisfake@wendysemailprovider.com' into the email field (112ms)
    ✓ Wendy enters 'password' into the password field (47ms)
    ✓ Wendy clicks on the login button (48ms)
# etc.
```

Does this make sense?

**Comment by KyleFairns** [comment]
Apparently I was stumbling on the issue due to defining them as interactions instead of tasks - but hadn't been able to find the 2.0 syntax for tasks before now (and didn't think it would be that simple)

Thanks for the help @jan-molak, and keep up the smashing work!

**Comment by jan-molak** [comment]
Hey guys, just to let you know, since Serenity/JS is eating up all the free time I have, I'm looking for alternative ways to sponsor its development going forward to make it more sustainable.

I thought I'd experiment with a [Github Sponsors profile](https://github.com/sponsors/jan-molak/) as a way to do it, so if you or your company find Serenity/JS useful, please consider buying me a coffee every now and then ;-)

**Comment by jan-molak** [comment]
@ctaepper,  @asnov, @owlran , @Ijee, @nbarrett, @abhinaba1080, @KyleFairns - thanks a million for helping me iron out the issues with Serenity/JS v2 🙇 

I'm happy to announce that the official release is now available on NPM and the new website at https://serenity-js.org.

Please give it a try and let me know your thoughts on [Twitter](https://twitter.com/JanMolak) and our new [Gitter Chat](https://gitter.im/serenity-js/Lobby)!

**Comment by abhinaba1080** [comment]
Yesterday i was checking that github was bombarded with commits... I knew
some big is coming... Thanks for all your hard work @jan

Version 2.0 will be a huge success.
