### ISSUE TITLE
help with three browsers!

### ISSUE THREAD

**Issue by AbhineetSharmax** [serenity-js/serenity-js#320]
Hi jan-molak,
 
I have automated large numbers of scenarios using Serenity JS and chrome, its really helping us understand the code, whenever someone new reads the code, he/she can easily understand whats happening in lines.

Now, I am trying automating using other two browsers, Chrome, FF, IE..

In everycase, chrome works fine.
FF works fine.
IE troubles sometimes with clicks, waits, sometimes works.
Is it a common problem, how can we achieve. sane script works proper for the three browsers..
need suggestion. Thank you.

Best Regards,
Abhineet Sharma

**Comment by jan-molak** [comment]
Hi Abhineet! It's great to hear that Serenity/JS is helping your team 😄 

From what you're saying I understand that Chrome and FF behave as expected, but you're seeing issues IE?

It's quite difficult to suggest anything without seeing your code and the errors you're seeing or knowing the details of your setup (browser version, OS, etc.).
What I can propose, however, is that since Serenity/JS builds on Protractor, any low-level and browser-related issues might have already been reported on the [angular/protractor issue tracker](https://github.com/angular/protractor/search?q=internet+explorer&type=Issues).
I see that there are quite a few [open issues related to IE](https://github.com/angular/protractor/search?q=internet+explorer&state=open&type=Issues) at the time of writing.

Does this help at all?
Jan

**Comment by abhinaba1080** [comment]
IE always gives you trouble.  One of the main reason probably IE still do not support ES6. So, here is some suggestions I want to provide,

use below capability for IE:

```ts
'internet explorer': {
    browserName: 'internet explorer',
    ignoreProtectedModeSettings: true,
    platform: 'ANY',
    version: '11',
    args: ['--silent', '--no-sandbox', '--test-type=browser', '--lang=US', '--start-maximized'], //,'--headless', '--disable-gpu',
    ensureCleanSession: true,
    nativeEvents: false,
    allowBlockedContent: true,
    'allow-blocked-content': true,
    ignoreZoomSetting: true,
    // to run n number of feature files in parallel, shardTestFiles -> true, maxInstances -> n
    shardTestFiles: process.env.RUN_TEST_PARALLEL === 'true',
    maxInstances: Number(process.env.MAX_BROWSER_INSTANCE)
  }
```

And you need to definitely switch off the directConnect. 

Then, if you use typescript, then you may want to trans-pile the ES6 specific codes to ES5, like:

```ts
{
  "compilerOptions": {
    "allowUnusedLabels": false,
    "baseUrl": ".",
    "lib": ["dom", "es6", "es7"],
    "declaration": false,
    "module": "commonjs",
    "moduleResolution": "node",
    "noImplicitAny": false,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "noEmitHelpers": true,
    "importHelpers": true,
    "outDir": "transform",
    "removeComments": false,
    "resolveJsonModule": true,
    "skipLibCheck": true,
    "sourceMap": true,
    "mapRoot": "transform",
    "esModuleInterop": true,
    "target": "es5",
    "typeRoots": ["./node_modules/@types"],
    "types": ["node", "cucumber"]
  },
  "exclude": ["node_modules", "typescript"]
}

```

Hope this will help.

**Comment by jan-molak** [comment]
Hi @AbhineetSharmax, @abhinaba1080's suggestions should help you to resolve the issue so I'll close this ticket. Please feel free to open a new one should you require further assistance.
