### ISSUE TITLE
Configure Screenshots

### ISSUE THREAD

**Issue by NicoForce** [serenity-js/serenity-js#474]
I have a few questions regarding the use of serenity-js:

1) **Is there a way to configure screenshoots taken by steps or tasks, such as being show in a [very old serenity bdd blog]**(https://johnfergusonsmart.com/serenity-bdd-tip-fine-tuning-screenshots-living-documentation/).

2) I modified [protractor-beautiful-reporter](https://www.npmjs.com/package/protractor-beautiful-reporter) so I could take screenshots outside the web, such as the desktop, or some excel sheet, so they could be automatically included in the final report. **Is there a way to automatically add a .png image to the report so it can be shown in the report** (or a similar idea)?

**Comment by jan-molak** [comment]
Sure, you won't need the `protractor-beautiful-reporter` as Serenity/JS provides you with much more thorough reporting and screenshot capabilities.

If you'd like to add Serenity/JS reporting to a non-Screenplay test suite, check out #362.
If you're the [Screenplay Pattern](https://serenity-js.org/handbook/thinking-in-serenity-js/screenplay-pattern.html) in your test suite, all you need to do in order to add screenshots to your reports is to add a [`Photographer`](https://serenity-js.org/modules/protractor/class/src/stage/crew/photographer/Photographer.ts~Photographer.html) to your Serenity/JS configuration.

Please note that the Serenity/JS template projects for [Jasmine](https://github.com/serenity-js/serenity-js-jasmine-protractor-template) and [Cucumber](https://github.com/serenity-js/serenity-js-cucumber-protractor-template) come configured to [produce the reports and take screenshots](https://github.com/serenity-js/serenity-js-jasmine-protractor-template/blob/master/protractor.conf.js#L25-L33) upon failure, so all you need to do is just write your tests.

Does this help?

Jan

**Comment by jan-molak** [comment]
Hey @NicoForce  - I haven't heard from you regarding this ticket for a while so I'm going to close it. Please feel free to re-open it if you need any further guidance.

**Comment by NicoForce** [comment]
Sorry for not answering @jan-molak.

I thank you for the information provided, I'll try to enhance serenity-js screenshoot taking capabilities for my project.

Thanks for closing the issue, as it's been solved.
