### ISSUE TITLE
Need support naively to get statusText querying LastResponse

### ISSUE THREAD

**Issue by abhinaba-ghosh** [serenity-js/serenity-js#511]
Hi @jan-molak ,

It would be nice if we can add another static method to get the statusText from the LastResponse. 
Example if a response consists "401, Invalid session token", statusText should return "Invalid session token"

**Comment by jan-molak** [comment]
Hey @abhinaba1080!

Sure; I don't typically assert on `statusText` since it's rather unlikely that the server would return something like say `200, Not found` 🤔 

Having said that, we could add it for completeness since axios itself [gives us access to it](https://github.com/axios/axios/blob/5189afff38dc0689ac0c1b1bfa51626bb8541709/index.d.ts#L76-L83).

How would you feel about raising a PR?

**Comment by jan-molak** [comment]
Hey @abhinaba-ghosh! I haven't heard from you in a while so I'm guessing you no longer need this feature and I can close this ticket?

**Comment by abhinaba-ghosh** [comment]
Yes @jan-molak , It's not a burning need anymore.
