### ISSUE TITLE
Non Screenplay terminal should show step status (passed tick / failed cross) in the terminal

### ISSUE THREAD

**Issue by abhinaba-ghosh** [serenity-js/serenity-js#515]
Hi @jan-molak ,

I am not getting real time status of the executed tests in the console. I am using serenity with the non-screenplay pattern. 

My config file says:

```
 serenity: {
    runner: 'cucumber',
    requirementsDirectory: `${process.cwd()}/test/e2e/features`,
    crew: [
      ArtifactArchiver.storingArtifactsAt('./target/site/serenity'),
      new SerenityBDDReporter(),
      ConsoleReporter.withDefaultColourSupport(),
      Photographer.whoWill(TakePhotosOfInteractions)
    ]
  }
```

The real-time console output I am getting:

![image](https://user-images.githubusercontent.com/23141842/77615697-f9ad2a00-6f55-11ea-9c78-2f4d24c9665a.png)

You can clearly see that although all steps are getting passed, I am not able to see the tick marks before the steps. It is blocking me to visualize the real-time status.

**Comment by jan-molak** [comment]
Hey @abhinaba1080, so that's an interesting one.

If you look at how the [`@serenity-js/console-reporter`](https://github.com/serenity-js/serenity-js/blob/986ae29d8f6dd5570955ddc17404dae9fc2abcb3/packages/console-reporter/src/stage/crew/console-reporter/ConsoleReporter.ts#L203) works, you'll see that it prints the name of the task when the task starts, and the name of the interaction together with its status (a tick, a cross, etc.) when the interaction finishes. 

Since Cucumber steps emit the same events as tasks (see [#362](https://github.com/serenity-js/serenity-js/issues/362#issuecomment-604759617)), their names are printed before the task is executed. At that point, we don't know their status, so there's no status to print.

The reasoning behind this design is that the status of a task depends on the status of the interactions that constitute it. While we _could_ print the status of both tasks and interactions, it would add a lot of noise to the output in screenplay-style scenarios.

If there's a huge interest in this feature, we could implement it as a config option.

**Comment by jan-molak** [comment]
Closing in favour of #1654, where we can discuss improvements to `ConsoleReporter`
