### ISSUE TITLE
Defining a global actor

### ISSUE THREAD

**Issue by gokul10cs12** [serenity-js/serenity-js#562]
hi @jan-molak  , I'm a newbie to serenity-js.
 I have a doubt and an issue.

 ```
const actor = actorCalled('Sandeep').whoCan(
        BrowseTheWeb.using(protractor.browser),
        CallAnApi.at('http://localhost:8080'),
    );
    it(`Test-1: helps us learn Serenity/JS`, () =>
        // grant ability / permission
        actor.attemptsTo(
                // re using the task
                EnsureTheServerIsUp(),
                OpenTheApp(),
                AddAnItemCalled(`Learn Serenity/JS`),
                // assertion
                Ensure.that(RecordedItems(), equals([
                    `Learn Serenity/JS`,
                    `Love 123!`,
                ])),
            ));
```
Whenever I define a global actor and run a test, the report could not capture the screenshot of the failure case. (Yes I configured the screenshot capture condition in protractoconf.js). Hope you would suggest a possible solution to the issue I'm facing.

**Comment by jan-molak** [comment]
Hey @gokul10cs12!

Have a look at the example test in the [`serenity-js-jasmine-protractor-template`](https://github.com/serenity-js/serenity-js-jasmine-protractor-template/blob/master/spec/example.spec.ts) project.

You'll notice that there is a `beforeEach` call that engages the `Actors` (a class that configures the `Actor` instances for your tests):
```typescript
    beforeEach(() => engage(new Actors()));
```
It is important to do this before each scenario, as in web-based tests each actor that has the `BrowseTheWeb` ability holds a reference to the `protractor.browser` object. Should you choose to restart your browser between the tests, this will then turn into an invalid reference and cause you trouble.

Once you have the `Actors` class (as per the [example](https://github.com/serenity-js/serenity-js-jasmine-protractor-template/blob/79cf8c39829bda71cc946a52125dce869a5f2edf/src/Actors.ts)), make sure to call the `actorCalled` function within your test rather than outside:
```typescript

    // This won't work:
    // const actor = actorCalled('Sandeep').whoCan(
    //     /* ... */
    // );

    it(`Test-1: helps us learn Serenity/JS`, () =>
        // This works:
        actorCalled('Sandeep').attemptsTo(
            // re using the task
            EnsureTheServerIsUp(),
            OpenTheApp(),
            AddAnItemCalled(`Learn Serenity/JS`),
            // assertion
            Ensure.that(RecordedItems(), equals([
                `Learn Serenity/JS`,
                `Love 123!`,
            ])),
        ));
```
Calling [`actorCalled`](https://serenity-js.org/modules/core/function/index.html#static-function-actorCalled) tells Serenity/JS which actor you're using (in Serenity-speak, it "puts the actor in the spotlight").

When [`Photographer`](https://serenity-js.org/modules/protractor/class/src/stage/crew/photographer/Photographer.ts~Photographer.html) (the service responsible for taking the screenshots) needs to take a screenshot, it checks which actor is active, and then uses their browser to take the screenshot.

Let me know if this helps!

Best,
Jan

**Comment by gokul10cs12** [comment]
Thank you @jan-molak . It was helpful.

Regards,
Gokul
