### ISSUE TITLE
Integration with other tools such as playwright, webdriverio

### ISSUE THREAD

**Issue by DicksengA** [serenity-js/serenity-js#563]
Was trying to integrate with webdriverio and was looking at the PhotoTakingStrategy class.

```typescript
browseTheWeb    = BrowseTheWeb.as(stage.theActorInTheSpotlight());
```

if we change it to AbilityToTakePhoto.as(stage.theActorInTheSpotlight());

```typescript
interface AbilityToTakePhoto{
    takeScreenshot():String;
    platform: Capabilities();
}
```

We can easily implement 
```typescript
BrowseTheWeb implements AbilityToTakePhoto
BrowseTheWebWithWebdriverIO implements AbilityToTakePhoto
BrowerTheWebWithPuppeteer implements AbilityToTakePhoto
```

Then separate the phototaking into serenity-core. 
This would make it easier to integrate with other tools? 
Since we can quickly test things out with puppeteer etc.
The actual implementations of Interactions annd Questions can be added slowly.

**Comment by jan-molak** [comment]
Hi @DicksengA!

As a result of the conversation at #493 I started to experiment with integrating Serenity/JS with WebdriverIO and Puppeteer. Check out the [E2E suite](https://github.com/jan-molak/authenticator-browser-extension/tree/55fa8b505f2ba6dcd7cf96dd22304765e31e1f99/e2e) of the [`authenticator-browser-extension`](https://github.com/jan-molak/authenticator-browser-extension) project to see those early prototypes.

I think we could approach what you're proposing in three steps:
1. Introduce a new `@serenity-js/webdriverio` module (probably marked as [experimental](https://serenity-js.org/handbook/integration/versioning.html#experimental-apis))
2. See how much we could port from `@serenity-js/protractor` with minimal changes (including classes like the `Photographer`, etc). 
3. Then maybe, if there's value in doing so, introduce another module with interfaces that `@serenity-js/protractor` and `@serenity-js/webdriver` could implement to help people switch between the different Web-testing-specific modules more easily (`@serenity-js/web`?).

The last point is a bit harder in TypeScript than it would've been in say Java because of [type erasure](https://github.com/microsoft/TypeScript/wiki/FAQ#what-is-type-erasure), so to have:
```typescript
BrowseTheWeb.as(stage.theActorInTheSpotlight());
```
return a driver-specific implementation like `BrowseTheWebWithWebdriverIO`, etc. we'd need to use some tricks with abstract classes and build something like Java SPI to look up the correct implementation based on the modules you're using, or have the `BrowseTheWeb` return the driver-specific implementation based on config.

Either approach to step 3 would require some careful thought and consideration, but I'd be happy to help out with steps 1 and 2 if there's enough interest in the community.

**Comment by DicksengA** [comment]
BrowseTheWebWithWebdriverIO i have briefly written this part.
I find the biggest difficulty is how tight the integration should be.
Separating the runner from the tool will be easier, so you can run webdriverio/cypress/puppeteer/playwright with serenityjs-cucumber, serenityjs-jasmine

**Comment by DicksengA** [comment]
Hi @jan-molak  i have tried to do a simple integration with puppeteer by creating 3 modules.

Photographer:
Tool will implement Takescreenshots.
An interface for photographer to get the AbilityForScreenshots

ToolManager
Interface ManagedTool for tool to define how to create and destroy tool (can be puppeteer,cypress, winappdriver etc)
Manages lifecycle of tool used by Implementing stagecrew
Destroys tool after Test or AfterSuite

Creation of tool will be handled in preparing the actors either as a static object if destroy after suite or instance when actor.can(ToolManager.create());

serenityjs-puppeteer:
Mapping of BrowserTheWeb and implementation of TakesScreenshots, ScreenshotAbilityProvider.
Implementation of ManagedTool from tool manager

I have managed to get it working. But struggling with the screenshots. It seems the current photographer is async therefore it takes photos of the interaction at a different snapshot from when the interaction completes.
Should this be synchronous?

Second is if i have multiple tools, example web, desktop app(winappdriver). i can only take screenshot from one tool since i have no way for knowing if the activity is related to which ability

**Comment by mpuertao** [comment]
I must add something:

I will speak of a playwright for several reasons:
1. We have more than 40k tests and more of 11k features with SerenityBDD in Java from Fergusson. But this has been chaos, since the particularities of the applications are important, and adapting this and times of execution is really tedious.
2. When we saw this problem, we found ourselves in the need to look for a tool or strategy that would allow us to improve both speed and efficiency, without omitting tests. There we found several allies: Serenity / JS, Protractor, WebDriverIO, but none of them could give us what we needed: "SPEED, ADHERENCE, USE CONTEXTS, DATA MEMORY CACHE, POLYGLOTE, MULTIBROWSER (DevKit), EMULATE for WEB on mobile, among many other characteristics within our use ".
3. Due to the insistence of looking for something that would really support our needs, we came across Playwright. Which allows all the aforementioned, and many more things.
The playwright team has been growing, they are giving it a lot of relevance and momentum from Microsoft, said by its leader.

So I think it's worth adding Playwright to Serenity / JS, to make use of live documentation, parallelization, and so on.

Thank you @janmolak for the contribution

**Comment by andreasmarkussen** [comment]
I have recently tried Playwright and I am also ready to work on getting Playwright supported in Serenity-JS.
It is dead fast! 

Has anyone started a branch on it?

**Comment by jan-molak** [comment]
> I have recently tried Playwright and I am also ready to work on getting Playwright supported in Serenity-JS.
> It is dead fast!
> 
> Has anyone started a branch on it?

Hi @andreasmarkussen! Sounds great, thanks for offering your help :-) 

@cipivanov has put together a prototype you can find in the [`authenticator-browser-extension` repo](https://github.com/jan-molak/authenticator-browser-extension/blob/master/e2e/playwright/chrome-authenticator-extension.spec.ts). It should be a good starting point. 

You can find my work on WebdriverIO on [`features/webdriverio` branch](https://github.com/serenity-js/serenity-js/tree/features/webdriverio).

Maybe have a look and let me know what you think on Gitter?

**Comment by andreasmarkussen** [comment]
We are doing a TV & Film app and we ran into issues on DRM since it requires loading compinents like Widevine DRM.

Playwright currently has the same issues.

Protractor and I assume WebdriverIO does not. 
I know that DRM is not needed for everyone, but it is essential for us.
So we are happy with the direction of WebdriverIO and I will try this out.

**Comment by jan-molak** [comment]
> We are doing a TV & Film app and we ran into issues on DRM in Cypress since it requires loading compinents like Widevine DRM.

Hey @andreasmarkussen - this is very interesting! I haven't worked with Widevine before, do I understand correctly it is a Chrome extension? Have you tried it with bog-standard WebdriverIO by any chance?

**Comment by andreasmarkussen** [comment]
> > We are doing a TV & Film app and we ran into issues on DRM in Cypress since it requires loading compinents like Widevine DRM.
> 
> Hey @andreasmarkussen - this is very interesting! I haven't worked with Widevine before, do I understand correctly it is a Chrome extension? Have you tried it with bog-standard WebdriverIO by any chance?

Yes - Just tried it yesterday  - works like a charm! I am in love with WebdriverIO and I think that it is a good replacement for Protractor as the strategic choice on the long perspective for SerenityJS

**Comment by nchursin** [comment]
How I missed this discussion before? :)

Guys, I started a [separate project](https://github.com/testmyorgdotcom/serenityjs-playwright) for Playwright integration. @jan-molak if you think that would work for a module inside the main repo, I can add it to the serenity/js project in a fork and send a PR.

It supports some very basic stuff ATM, but I'm working on adding functionality

**Comment by jan-molak** [comment]
@nchursin - sounds awesome! Yes, I think a `@serenity-js/playwright` module would be a great addition to the family 😊  Thanks for offering to help!

Have a look at the [`features/webdriverio`](https://github.com/serenity-js/serenity-js/tree/features/webdriverio/packages) branch, please; I'm trying to make the `@serenity-js/webdriverio` Interactions and Questions compatible with `@serenity-js/protractor` to make it easy for people to swap out the implementations. I've also cleaned up a lot of internal code, especially around handling [`Lists`](https://github.com/serenity-js/serenity-js/blob/features/webdriverio/packages/core/src/screenplay/questions/List.ts), which should be useful for the Playwright module.

You might also want to join our brand new [Contributors channel](https://gitter.im/serenity-js/Contributors) on Gitter to discuss the details!

**Comment by jan-molak** [comment]
Closing as Serenity/JS v3 supports both Playwright and WebdriverIO 🎉 https://serenity-js.org
