### ISSUE TITLE
Is it possible to store value of text in variable using Text.of(Target)

### ISSUE THREAD

**Issue by Manishrn** [serenity-js/serenity-js#564]
Hi @jan-molak 

I am trying to get the text value using Text.Of, when I try to log the value on console it throws ✗ TypeError: Cannot read property 'toString' of undefined error.

Could you please help me with this ?

Regards,
Manish

**Comment by jan-molak** [comment]
Sure, could you please provide an example of how you try to do it that results in an error?

**Comment by Manishrn** [comment]
Hi @jan-molak 

Thank you for reply,

below is the code : 
var text = Text.of(element)
        return actor.attemptsTo(
            console.log(text)
        );

Regards,
Manish

**Comment by jan-molak** [comment]
Gotcha, the first thing you'll need is an interaction to [`Log`](https://serenity-js.org/modules/core/class/src/screenplay/interactions/Log.ts~Log.html). This is how you can log a given value or an answer to a [`Question`](https://serenity-js.org/modules/core/class/src/screenplay/Question.ts~Question.html) logged to both the terminal and the HTML report.

```typescript
const target = Target.the('element of interest').located(by.css('.some-class'));

actorCalled('Alice').attemptsTo(
    Log.the(Text.of(target)),
    Log.the('you can also provide a static value here'),
    Log.the('or', 'several', 'values')
);
```

Now, since everything in Serenity/JS is asynchronous, calling:
```typescript
var text = Text.of(element)
```
will simply assign a [`Question`](https://serenity-js.org/modules/core/class/src/screenplay/Question.ts~Question.html) about the [`Text`](https://serenity-js.org/modules/protractor/class/src/screenplay/questions/text/Text.ts~Text.html) of the [`Target`](https://serenity-js.org/modules/protractor/class/src/screenplay/questions/targets/Target.ts~Target.html) to a variable. 

But that's probably not what you want.

If you simply want the actor to remember the value at some point in the scenario and then recall it later on to perhaps enter into some form field or compare with another value, what you need is to teach your actor to [`TakeNotes`](https://serenity-js.org/modules/core/class/src/screenplay/abilities/TakeNotes.ts~TakeNotes.html)

Does this help?

**Comment by Manishrn** [comment]
Hi @jan-molak 

Thank you for response,
I want to implement second aaproach which you mentioned, where I want to store text value  of an element and compare it in if so that depending on the condition it will do necessary actions.

return actor.whoCan(
                    BrowseTheWeb.using(protractor.browser),
                    TakeNotes.usingAnEmptyNotepad()
);
as in above code actor has ability to TakeNotes, but not sure how it store the value in Task implemetation. 

Regards,
Manish

**Comment by jan-molak** [comment]
Hey @Manishrn,

Please check out the [API docs](https://serenity-js.org/modules/core/class/src/screenplay/abilities/TakeNotes.ts~TakeNotes.html) I've linked earlier.

```typescript
 import { Note, TakeNote, TakeNotes } from '@serenity-js/core'
 import { BrowseTheWeb, Target, Text } from '@serenity-js/protractor'
 import { by, protractor } from 'protractor';

 class Vouchers {
     static code             = Target.the('voucher code').located(by.id('voucher'));
     static appliedVoucher   = Target.the('voucher code').located(by.id('applied-voucher'));
 }

 const actor = Actor.named('Noah').whoCan(
     TakeNotes.usingAnEmptyNotepad(),
     BrowseTheWeb.using(protractor.browser),
 );

 actor.attemptsTo(
     // (1)
     TakeNote.of(Text.of(Vouchers.code)),    
     // ... add the product to a basket, go to checkout, etc.

     // (2)
     Ensure.that(Text.of(Vouchers.appliedVoucher), equals(Note.of(Text.of(Vouchers.code)))),
 );
```

The interaction to `TakeNote.of(Text.of(Vouchers.code))` makes the actor remember the value of `Text.of(Vouchers.code)`, and the question about `Note.of(Text.of(Vouchers.code))` retrieves that remembered value.

To see how this works, try the below example:

```typescript
actor.attemptsTo(
    TakeNote.of(Text.of(Vouchers.code)),        // remembers the value
    Log.the(Note.of(Text.of(Vouchers.code)),    // logs the remembered value
);
```

You can also re-use that `Note` in other contexts, for example:

```typescript
actor.attemptsTo(
    TakeNote.of(Text.of(Vouchers.code)),
    Enter.theValue(Note.of(Text.of(Vouchers.code)).into(someFormField),
);
```

Does this help?

**Comment by Manishrn** [comment]
Hi @jan-molak ,

Yes, document helpled me to understand how TakeNote works, I tried the same yesterday.
However scenario I am trying to achive here is bit different.
I want to pass the month value from steps, so that in Task when I match that value with the value which I am getting from UI it should stop else it should do something.

**Steps **

When(/^(?:he|she|they) select the "([^"]*)" month$/, (month: string) =>
    actorInTheSpotlight()
        .attemptsTo(
            MonthSelection.selectMonthFromCalendar(month)
        )
);

**Task**

        TakeNote.of(Text.of(CalendarControls.txtMonth))
        let mothValue = Note.of(Text.of(CalendarControls.txtMonth))
        if (mothValue === this.month) {
            return actor.attemptsTo(
                //stop 
            )
        }
        else {
            return actor.attemptsTo(
                // do something else
            )
        }
    }

**UI screenshot**
![image](https://user-images.githubusercontent.com/24430750/81896094-6d23fd00-95d1-11ea-9ebe-30481fc8ffef.png)



I have achieved same scenario in protractor.

for (let i = 0; i < 12; i++) {
            element(by.xpath(elementCalendarMonthText)).getText().then((monthValue) => {
                if (monthValue === "DECEMBER 2020") {
                    return;
                }
                else {
                    element(by.xpath(elementChangeMonth)).click()
                }
            })
        }

Regards,
Manish

**Comment by jan-molak** [comment]
Right, the issue is in the task implementation.

The construct `TakeNote.of(Text.of(CalendarControls.txtMonth))` creates an instance of an `Interaction` that has to be given to an actor to perform.

For example, this works:
```typescript
actor.attemptsTo(
    TakeNote.of(Text.of(CalendarControls.txtMonth)),
),
```

This won't work:
```typescript
let thisIsAnInteraction: Interaction =  TakeNote.of(Text.of(CalendarControls.txtMonth)),
```

For the same, this won't work either:
```typescript
let thisIsAQuestionNotAString: Question = Note.of(Text.of(CalendarControls.txtMonth))
```

What you need in your case is a [conditional statement](https://serenity-js.org/modules/assertions/class/src/Check.ts~Check.html) in your actor flow (the sequence of interactions and tasks you pass to `attemptsTo`):

```typescript
import { Check, equals } from '@serenity-js/assertions';

actor.attemptsTo(
    Check.whether(Note.of(Text.of(CalendarControls.txtMonth)), equals('December'))
        .andIfSo(
            TaskToPerformWhenTheConditionIsMet(),
        )
        .otherwise(
            TaskToPerformWhenTheConditionIsNotMet(),
        )
);
```

Does this help?

**Comment by Manishrn** [comment]
@jan-molak 

Works like a charm :) .
Its always a new learning whenever I interact with you, Thanks a ton !!!!

One more query I have here is, is it possible to repeat a particular Task in loop or is there any conditioning available which will repeat the Task until it reaches to a particular break condition.


Regards,
Manish

**Comment by jan-molak** [comment]
Excellent, I'm glad it helped!

There's nothing built-in to support loops (yet!), but please feel free to raise a ticket to request it. 
If you could also provide an example in that new ticket that shows how you'd like to use it that would be grand.

Best,
Jan
