### ISSUE TITLE
removed '--disable-extensions' still not load any extension when running the automation test

### ISSUE THREAD

**Issue by lucieneven** [serenity-js/serenity-js#604]
Hello, 

I was wondering how I can load Chrome extension when running automation test. Before that, I assure that those extension was loaded normally when launch the incognito Chrome manually. However, like said, even I removed the lines of '--disable-extensions' from goog:chromeOptions of protractor.conf.js, but still no extension loaded when running the test.

'goog:chromeOptions': {
            args: [
                '--incognito',
                // '--headless',
                '--no-sandbox',
                '--disable-infobars',
                // '--disable-extensions',
                '--log-level=3',
                '--disable-gpu',
                '--window-size=1920,1080',
            ].concat(isCI ? ['--headless'] : []),
            'w3c': false    // run in headless mode on the CI server
        }

![image](https://user-images.githubusercontent.com/10438908/85630359-788f2d00-b641-11ea-820b-97c8d45962a7.png)

Some information are as follows:

Chrome Version 83.0.4103.106 (Official Build) (64-bit)
macOS Catalina, Version 10.15.5
node v11.15.0
serenity-js, 2.1.5 I guess.

Please shed some light how to load extension into incognito Chrome when running the automation test. Since we see the '--disable-extensions' here, it means we can work around to enable extension?

Thanks so much!

Lucien

**Comment by Ijee** [comment]
I think the problem is that you have to explicitly allow an extension to be used with the incognito mode. If not it will not be used during your test.

**Comment by jan-molak** [comment]
Hi @lucieneven!

There are three things you need to know about Chrome and extensions:
- The default extensions from your regular profile won't be loaded in the incognito mode, so you need to explicitly specify what extensions you want for your tests (which is a good thing since you want your tests to yield reproducible results)
- If you want to use extensions with non-headless Chrome, you need to specify them as base64-encoded strings.
- Chrome doesn't support browser extensions when running in [**headless mode**](https://developers.google.com/web/updates/2017/04/headless-chrome) and Chrome developers have [decided against](https://bugs.chromium.org/p/chromium/issues/detail?id=706008#c5) implementing this feature in any near future due to the complexity of the task.

If you'd like an example of how to configure Protractor to use an extension, check out the [`Authenticator`](https://www.npmjs.com/package/authenticator-browser-extension) extension I've written.

Hope this helps!
Jan
