### ISSUE TITLE
The SerenityJs framework is not picking the JS step deffenition

### ISSUE THREAD

**Issue by rakeshnambiar** [serenity-js/serenity-js#698]
The SerenityJs framework is not picking the JS step deffenition whereas on the same suite the TS step defnition available and that's working fine.

`Repo to reproduce the issue`
https://github.com/rakeshnambiar/serenitjs-v2-js

Please change the `baseUrl` and `cucumber tag` in order to run the ts demo script.

**Comment by jan-molak** [comment]
Thanks for providing the sample repo! It looks like to me that the code mixes Cucumber 1 and Cucumber 6-style step definitions.

You'll notice that the [TypeScript version](https://github.com/rakeshnambiar/serenitjs-v2-js/blob/master/features/step_definitions/super_calculator.steps.ts#L4) uses:
```
import { Before, Given, Then, When } from 'cucumber';
```

while the [JavaScript version](https://github.com/rakeshnambiar/serenitjs-v2-js/blob/master/features/step_definitions/submission.wizard.steps.js#L23) uses:
```
    this.Given(/^I am an Admin user$/, async () => {
```

Since Cucumber 6 no longer loads Cucumber 1-style step defs, so they appear to be undefined.

I'd suggest either changing the imports in your JS code to use Cucumber 6 style step defs:

```
// bad
module.exports = function submitManuscriptSteps() {
    this.Given(/^I am an Admin user$/, async () => {

```

```
// good
const { Given } = require('cucumber';

Given(/^I am an Admin user$/, async () => {
```

Or if that's not possible, downgrading Cucumber to version 1.

My personal recommendation would be to upgrade step defs to Cucumber 6, but it's up to you. Either will work.

**Comment by rakeshnambiar** [comment]
Thanks, It's worked. I change the script to make it compatible to Cucumber 6 as you recommended.

**Comment by rakeshnambiar** [comment]
@jan-molak Unfortunately the HTML report is not generated fully and I can see the below-mentioned error.

```
[test:report] 10:00:11.207 [main] WARN  n.t.c.r.h.HtmlAggregateStoryReporter - Failed to generate report for net.thucydides.core.reports.html.HtmlTestOutcomeReportingTask@26f1249d - java.util.concurrent
.ExecutionException: java.lang.NullPointerException
```

**Comment by rakeshnambiar** [comment]
Same suite I had executed on a docker with `/usr/lib/jvm/java-8-openjdk-amd64` and it's successfully. However, I can't see any scenario level details or screenshot (I can't see the screenshots on the path). Seems it's again the screenshot issue mentioned on https://github.com/serenity-js/serenity-js/issues/362
