### ISSUE TITLE
Protractor Serenity BDD html report issue

### ISSUE THREAD

**Issue by rajkumar571** [serenity-js/serenity-js#718]
Please clarify below queries:
**Question1:**
Screenshots are not coming for every feature step In  serenity bdd html report. It’s coming only at the final step of “takes screenshot of...”
 #Please suggest how to see screenshots for every feature step in the report. Please see below html report screenshot.

![3B489BA9-3FDD-479E-B550-9D3795A19924](https://user-images.githubusercontent.com/76705244/103386096-d1dd8a80-4ac2-11eb-9462-1904bc3bf342.jpeg)

below is the code to take the screenshot which I am using:

![256D2D14-4521-497E-B46E-8AF6089719F0](https://user-images.githubusercontent.com/76705244/103386222-7e1f7100-4ac3-11eb-9408-6b9028f63ff5.jpeg)

**Question2:**
In API call, array value which is showing it as [object, object] in serenity bdd html report while click on Rest Query button. My doubt is how can i see array value as key:value pair instead of [object , object].

**Comment by jan-molak** [comment]
Hey @rajkumar571!

The reason you're only seeing a screenshot attached to an `after` step is that you're only taking the screenshot in that step...

There is a workaround and a solution to this problem:
- workaround - use [`AfterStep`](https://github.com/cucumber/cucumber-js/blob/master/docs/support_files/hooks.md#beforestep--afterstep) instead of `After`
- solution - use the Screenplay Pattern and configure the `Photographer.whoWill(TakePhotosOfInteractions)`

I'm naturally advocating for you to try and use Screenplay 😊 

Re question 2 - could you please raise a separate ticket providing the response you're trying to log so that I can try to reproduce? Thanks!

**Comment by rajkumar571** [comment]
Thanks for your reply!

In my project we are following non screenplay approach and framework implemented using non screenplay.

Also you mentioned below
workaround - use AfterStep instead of After
But AfterStep annotation is showing error when I try to use this annotation. When I type in auto suggestion this option not showing.

Could you please provide any workaround for getting screenshot using non screenplay approach.

Thanks
