### ISSUE TITLE
Question -  Check.Whether method

### ISSUE THREAD

**Issue by Krithikmano** [serenity-js/serenity-js#720]
Use case - one of the page, couple of elements are dynamically displayed based on certain condition. First i need to check first element is present, if so i have to select that element and proceed further, else  i  have to choose the other element and proceed further. I used the below method for testing this scenario

Check.whether(Target1, isVisible()).andIfSo(Click.on(Target)).otherwise(Click.on(Target))

while running the script, first condition is not met .Hence, flow is interacting with second condition and proceeded further. In the report it is showing the assertion error for the first condition and overall result is showing failed.

In the above case, logically my script is passed but in the report it is showing failure due to that error. Is there any way we can exclude the error message in the report?

**Comment by jan-molak** [comment]
Hey @Krithikmano could you create a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) on GitHub based on one of the Serenity/JS template projects so that I can try to reproduce?

**Comment by Krithikmano** [comment]
@jan-molak I can’t share my project code here. But I will give you the reproducible steps here


Check.whether(TargetElement, isVisible()).andIfSo(Click.on(TargetElement)).otherwise(Click.on(TargetElement))
 
In the above code
1. Enter the incorrect Targetelement in whether method
2. Enter the correct Target Element in otherwise method
3. Run it and see the serenity report

**Comment by viper3400** [comment]
I'm using this pattern myself without errors (Serenity/JS version 2.19.10). In my example I'm checking for a problem dialogue to appear, and if so, I'll accept and close it, otherwise I'll do some logging:

Task:
![grafik](https://user-images.githubusercontent.com/11006334/104042010-2d51fb80-51da-11eb-9c25-22330a3347ad.png)

Console Report:
![grafik](https://user-images.githubusercontent.com/11006334/104042033-3773fa00-51da-11eb-8a90-6f8cbb87bf60.png)

So maybe you could provide the error message you've got?

**Comment by Krithikmano** [comment]
@viper3400 it is working as expected. So closing this issue.
