### ISSUE TITLE
Axios get call - Network issue

### ISSUE THREAD

**Issue by Krithikmano** [serenity-js/serenity-js#725]
When I try to hit the endpoint in postman . I could see proper response. The same I have used with serenity framework by using GetRequest method and I am getting below. I included the proxy Information in the header too

I verified all the headers and url and all are given correct

![A1DDB50A-42A6-4A22-BB8E-6EA51AD32987](https://user-images.githubusercontent.com/28629290/105447543-06fc7900-5c3a-11eb-9704-eff95569b9d6.jpeg)

**Comment by jan-molak** [comment]
Hey @Krithikmano, you mention proxies, have you configured the `axios` client used with Serenity/JS to use proxies?
See [my article](https://janmolak.com/node-js-axios-behind-corporate-proxies-8b17a6f31f9d) and let me know if it helps.

Best,
Jan

**Comment by Krithikmano** [comment]
@jan-molak 

I tried with the post operations and I could see proper response. 

I tried with few get operations and all are showing the same network error. ( I included few additional headers as per our project requirement)

I am bit confused why it is not working for get call and working only for post call

I am using serenity 2.19.4 version

Could you check from your end whether GetRequest is working fine.

**Comment by jan-molak** [comment]
Hi @Krithikmano, I'm fairly confident `GetRequest` is working fine, which you can see demonstrated not only in the [automated tests](https://github.com/serenity-js/serenity-js/tree/master/packages/rest/spec/screenplay) for the `@serenity-js/rest` module, but also in this [template project](https://github.com/serenity-js/serenity-js-cucumber-template) and its [Serenity BDD report](https://serenity-js.github.io/serenity-js-cucumber-template/) 😉 

I'd suggest simplifying the problem you're trying to solve and writing a minimalistic test that sends a get request to a known working end-point, i.e. `http://example.org`. 

If you believe there's a bug in Serenity/JS, I'd be grateful if you could create a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) using a [Serenity/JS template](https://github.com/serenity-js/serenity-js-cucumber-template) so that I can try to reproduce it.

Thanks!
