### ISSUE TITLE
Randomly receiving: "TypeError: Cannot read property 'map' of undefined"

### ISSUE THREAD

**Issue by dpkano** [serenity-js/serenity-js#76]
Hi,
      After a while the execution starts to skip the tests displaying this error (randomly):

```
Step: Before
    Step Definition: node_modules\serenity-js\src\serenity-cucumber\stage_cue.ts:6
    Message:
      TypeError: Cannot read property 'map' of undefined
          at reportFileNameFor (at $PATH\\node_modules\@serenity-js\core\src\reporting\serenity_bdd_reporter.ts:61:28)
          at $PATH\node_modules\@serenity-js\core\src\reporting\serenity_bdd_reporter.ts:52:63
          at Array.map (native)
          at at $PATH\\node_modules\@serenity-js\core\src\reporting\serenity_bdd_reporter.ts:51:39
```

   After the first Scenario that fails at this error, all the following Scenarios are skipped.

Daniel

**Comment by BlacktoBlue** [comment]
I am also getting this error, it seems to me when my tests are sharded. All tests on a shard following a failed tests then are erroring with this error. Perhaps restart browser between tests (#56) would solve this but that is still awaiting a fix from protractor

**Comment by jan-molak** [comment]
Hey @dpkano and @BlacktoBlue - this turned out to be a synchronisation error in the Serenity/JS 1.x implementation of the `SerenityBDDReporter`. [Serenity/JS 2.0](https://serenity-js.org) ships with a [completely re-written reporter](https://serenity-js.org/modules/serenity-bdd) that no longer has that issue.

Please check it out and let me know what you think!

Thanks for your patience and support.
Jan
