### ISSUE TITLE
Report generation in Docker fails with 'The “path” argument must be of type string'

### ISSUE THREAD

**Issue by anhaley** [serenity-js/serenity-js#802]
I have a Serenity-JS project that runs normally on the command line. I am trying to package it into a Docker container for use in an Azure pipeline, which is a model we've used with other projects.

However, when I run the project via Docker, the tests execute correctly but the step to generate report documentation fails with a rather terse error:

```
[test:report] > serenity-bdd run
[test:report] 
[test:report] I'm terribly sorry, but something didn't go according to plan:
[test:report] The "path" argument must be of type string. Received null
```

Nothing else shows up in the output, so the source of the issue isn't clear. I'm not even sure which `path` argument this is referring to. I've dug into the Serenity-JS Node module but I don't see a clear culprit here, nor do I understand why it would work via command line but not in Docker. Any insight would be greatly appreciated. Thanks!

**Comment by jan-molak** [comment]
Hey @anhaley - it's hard to tell without seeing the code, I'm afraid. Here's the [`run` command](https://github.com/serenity-js/serenity-js/blob/master/packages/serenity-bdd/src/cli/commands/run.ts), it uses `Path` objects in several places, so that might be a good starting point to debug it...

**Comment by anhaley** [comment]
@jan-molak thanks for your response. I have modified the starter demo into a simple demonstration of the issue. The repository is available [here](https://github.com/anhaley/serenity-js-docker-issue-demo); simply check it out and run `docker build .` to see the error triggered by `serenity-bdd run`.

**Comment by viper3400** [comment]
Hi @anhaley 

The the serenity-bdd cli is a Java application. Is there a Java runtime installed in your Docker container? Seems not like if I look into your demo Dockerfile?

https://github.com/serenity-bdd/serenity-cli

**Comment by viper3400** [comment]
@anhaley Try the following `Dockerfile` for your project, set the timezone in `ENV TZ=` to your desired timezone.

```
FROM ubuntu:latest

ENV TZ=Europe/Zurich
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN apt update && apt install -y nodejs npm openjdk-8-jdk

COPY . .

RUN npm i 
RUN npm run postinstall
RUN npm test
````

* I don't know, why you do the npm commands directly in the Dockerfile, but I think this is for demonstration purpose only.
* In the Docker environment the `serenity-bdd update` command in the `postinstall` script run into some issues when triggered directly by the `npm install`. 
  * This seem to be an issue with Alpine and Ubuntu as well. When started the `npm run postinstall` a second time (out of the context of the install process) it works. 
  * I don't analyzed this further for now.
* I'd to change from Alpine to Ubuntu, because the openjdk Java installation comes with some sybolic links.
  * The reporter uses the npm package `find-java-home` , which uses the `which` package, which wraps up the `lstat` linux function
  * I assume, that this lstat call points not to the correct directory, but didn't analyze this further.
  
 Hope, this helps a bit.

**Comment by anhaley** [comment]
@viper3400 Thanks for the response. Your solution works, and the callout about the Java runtime is a good one. I'm not jazzed about using the Ubuntu image since it's much bulkier and slower than we need, but identifying a working solution gives me somewhere to start from. Thanks!

**Comment by viper3400** [comment]
@anhaley Agreed with the Ubuntu thing. Just ran into this other symlink issue when trying to install Java into the Alpine image. I had have not time to have a deeper look into this. Using Ubuntu was just a quick proof that this is not a problem in general and to provide you a running example.  But would be cool to have it running in your base image as well!
