### ISSUE TITLE
Get the text of an element as String

### ISSUE THREAD

**Issue by tsche123** [serenity-js/serenity-js#881]
Is there any way to get the text of an element as String?
I have a test scenario, where I call an url address, as example `http://mywebsite.com/1234string`. But I need to get the `1234string` from an element from the page. 
When I use `TakeNote.of(Text.of(myElement))` (or just simply `Text.of(myElement)`) and then paste it into the url address, I get `http://mywebsite.com/a note of the text of myElement`.

**Comment by viper3400** [comment]
Hi @tsche123, I think you have to use `map`, have a look here: https://gitter.im/serenity-js/Lobby?at=605bd0c18478e061b95a813f

**Comment by jan-molak** [comment]
@viper3400 is right to use [`Question.map`](https://serenity-js.org/modules/core/class/src/screenplay/Question.ts~Question.html#instance-method-map), for example with [`replace`](https://serenity-js.org/modules/core/function/index.html#static-function-replace):

Something like this should do the trick:
```typescript
Text.of(myElement).map(replace(/.*\//, '')
```

Hope this helps!

**Comment by tsche123** [comment]
Hi guys, thank you for your answers, but unfortunately it's not working, I still get the same text.
When I use `Log.the(Note.of('myElement'))`, I get: 
````
✓ John logs: a note of myElement (1ms)
        a note of myElement:
        '1234string' 
````

But when I want to add `1234string` to my url address as:
````
https://mywebsite.com/ + Note.of('myElement').map(replace(/.*\//, '')) 
````

Unfortunately I still get `https://mywebsite.com/a note of myElement`

**Comment by jan-molak** [comment]
This behaviour is, in fact, correct.

A `Note` is a `Question`, so an `object`.

If you try to concatenate a `string` with an `object`, JavaScript will look up the [`toString()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/toString) method on the object and assume that this is what you had in mind.

This means that JavaScript understands this:
```
Navigate.to('https://mywebsite.com/' + Note.of('myElement').map(replace(/.*\//, '')))
```
as that:
```
Navigate.to('https://mywebsite.com/' + Note.of('myElement').map(replace(/.*\//, '')).toString())
```
and that's why you get:
```
"https://mywebsite.com/a note of myElement"
```

You have several ways to achieve what you need.

## `replace`

You can change how you invoke `replace` to inject the URL:

```
Navigate.to(Note.of('myElement').map(replace(/.*\//, 'https://mywebsite.com/')))
```

## A custom `Question`

You can create a custom `Question` that does the concatenation:

```typescript
import { Question, replace } from '@serenity-js/core';

const WebsiteUrlFor = (path: Answerable<string>) =>
    Question.about('website url', actor => async {
        const section = await actor.answer(path);  // returns a Promise so you need an await or .then
        return `https://mywebsite.com/${ path }`;
    });
```

Then call it:
```typescript
Navigate.to(WebsiteUrlFor(Note.of('myElement').map(replace(/.*\//, ''))))
```

You could also create a `Question` to extract the path element of the URL:

```typescript
const PathFrom = (url: Question<string>) =>
    Question.about(`path from ${ url }`, actor => async {
        const section = await actor.answer(websiteSection);  // returns a Promise so you need an await or .then
        return url.replace(/https?:\/\/.*?\//, ''))
    });
```

Then:
```typescript
Log.the(PathFrom(Note.of(myElement)))
Navigate.to(WebsiteUrlFor(PathFrom(Note.of(myElement))))
```

And so on.

## `q`

You can also use a helper function called [`q`](https://serenity-js.org/modules/core/function/index.html#static-function-q) which turns a [template literal](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals) into a `Question` object:

```typescript
Navigate.to(q`https://mywebsite.com/${ Note.of('myElement').map(replace(/.*\//, '')) }`)
```
And also:
```typescript
Navigate.to(q`https://mywebsite.com/${ PathFrom(Note.of('myElement')) }`)
```

---

Does it help?

**Comment by jan-molak** [comment]
Hi @tsche123, I haven't heard from you in a while so I'm assuming that I've answered your question. If not, please feel free to reopen this ticket or join [Serenity/JS Community Chat](https://gitter.im/serenity-js/Lobby).
