### ISSUE TITLE
Using cucumber-js and Serenity-js, the report doesn't show the assertion error details 

### ISSUE THREAD

**Issue by avi-ran** [serenity-js/serenity-js#887]
I'm currently building functional tests based on the template [serenity-js-cucumber-template](https://github.com/serenity-js/serenity-js-cucumber-template) but to be homogenous with other existing functional tests developed by my colleagues in other languages, I don't use the screenplay pattern. Instead, I'm doing simple assertions using Node's module 'assert'. For example on a ***Given*** step, I have the following assertion:

```js
import assert = require('assert');
// [...]
Given('opc-ua server is running and no test program is loaded',
    {timeout: 2 * 5000},
    async () => {
        assert.strictEqual(await killTestProgram(), 'SSH_CMD_SUCCEEDED');
});
// [...]
```

For this step, in my cucumber-js report, on failure, I have the following result: 
<img width="574" alt="ssh_pb" src="https://user-images.githubusercontent.com/84993870/123518466-568e1780-d6a6-11eb-9084-8b43ec0ad30c.png">

But in the Serenity report, I don't have the details about the Assertion error:
<img width="1368" alt="assert-result" src="https://user-images.githubusercontent.com/84993870/123518496-71608c00-d6a6-11eb-8cdc-2854eee12231.png">

**Comment by jan-molak** [comment]
This is related to https://github.com/cucumber/cucumber-js/issues/1453

With the changes introduced in Cucumber 7, error details are now a pretty-printed string instead of a stack trace - [src/runtime/step_runner.ts](https://github.com/cucumber/cucumber-js/blob/17b43911898e50b5077619005223f716c995c877/src/runtime/step_runner.ts#L74)

Let's see if I can somehow work around this 😞
