### ISSUE TITLE
Migration to WDIO: Public property 'method' of exported class has or is using name 'ElementAsync' from external module "./node_modules/webdriverio/build/types" but cannot be named.ts(4029)

### ISSUE THREAD

**Issue by viper3400** [serenity-js/serenity-js#946]
Hi @jan-molak 

As already discussed at Gitter, I've started a little WDIO migration game on our existing Protractor projects. Now I got an error, which possibly caused more by our project overall setup than by Serenity/JS at all.  As this is a bit more complex, let me explain the setup first:

* Our projects have a structure where all specs are under ```./spec``` and all ```Target```s, ```Task```s and so on are under ```./src```.
* I took the [template](https://github.com/serenity-js/serenity-js-mocha-webdriverio-template) and created  a demo repo here: https://github.com/viper3400/serenity-js-wdio-demo
* Because we have to test our application with different languages, I've created a ```translateTo``` function as discussed [at Gitter](https://gitter.im/serenity-js/Lobby?at=603e7d76b5131f4f28e9d538)
and implemented [here](https://github.com/viper3400/serenity-js-wdio-demo/blob/d7dbf9526b4a0cac8ee04d16e8526eaa5e9a5a2e/src/translateTo.ts).
* The language for the test run is set in the [spec file](https://github.com/viper3400/serenity-js-wdio-demo/blob/d7dbf9526b4a0cac8ee04d16e8526eaa5e9a5a2e/spec/example.spec.ts#L13) as ```locale```.
  * Normally this is set from the conf file as a global parameter in the ```browser``` object
* While nearly all of your examples export ```const``` Tasks and Targets, I've create a class for all Targets and a class for all Tasks, which belong to a special feature in our application.
  * This is, because I inject the locale into the class constructor an init the `translateTo` function from within the class instance.
  * So, we have no target references in our spec files, just references to tasks
  * I also need the ```locale``` at the target level, because there are cases, I don't want to the key for the translation string in the spec at all.
 * Though this may not be the intended style, this worked out for us with Protractor. 
 * I've tried to created some flavors of this in the demo repo.

This was just for explanation so far, now the real problem:
* We already had a [short chat](https://gitter.im/serenity-js/Lobby?at=610d0e5f7555e33351f85ba6)
* You've changed the rootDir to ```./spec``` in the template.
* Given by our project structure I have to have our ```./src``` as rootDir as well: https://github.com/viper3400/serenity-js-wdio-demo/blob/d7dbf9526b4a0cac8ee04d16e8526eaa5e9a5a2e/tsconfig.json#L11
  * Without this, the imports in ```example.spec.ts``` would have errors:
  * ```Cannot find module './custom.translations' or its corresponding type declarations.ts(2307)```
  * ```Cannot find module './translateTo' or its corresponding type declarations.ts(2307)```
* But with putting the ./src into the rooDirs I got an error at this line: https://github.com/viper3400/serenity-js-wdio-demo/blob/d7dbf9526b4a0cac8ee04d16e8526eaa5e9a5a2e/src/custom.targets.ts#L16
  * ```Public property 'GetingStartedButtons' of exported class has or is using name 'ElementAsync' from external module "c:/dev/git/_playground/serenity-js-wdio-demo/node_modules/webdriverio/build/types" but cannot be named.ts(4029)```

So, as I didn't dive into the deep of TS at all, I'm not sure whats the issue here. Would appreciate some input.
Thanks in advance
Jan

**Comment by jan-molak** [comment]
Hi @viper3400

I think the issue here might be [those lines here](https://github.com/viper3400/serenity-js-wdio-demo/blob/master/src/custom.targets.ts#L11-L16):

```typescript
    GetingStartedButton = Target.the('button for getting started').located(by.linkText(this.t('START_BUTTON')));
    
    // eslint-disable-next-line @typescript-eslint/explicit-module-boundary-types
    GenericButton = (linkText: string) => Target.the(`button with linkText ${linkText}`).located(by.linkText(linkText));
    
    GetingStartedButtons = Target.all(`buttons for getting started`).located(by.linkText(this.t('START_BUTTON'))).first();
```

The error states:
```
Public property 'GetingStartedButtons' of exported class has or is using name 'ElementAsync' 
from external module "c:/dev/git/_playground/serenity-js-wdio-demo/node_modules/webdriverio/build/types" 
but cannot be named.ts(4029)
```

The issue is actually quite well explained in [this post](https://github.com/microsoft/TypeScript/issues/9944#issuecomment-244448079):

> There is no explicit type annotation on the functions or variables. the declaration emitter infers their type and tries to write it. if the type is coming from a different module, then a. it needs to add an import or b. error.
> 
> The emitter can write the additional import, but that would have been changing your API shape in a way you did not indicate clearly in your code. so we opted to error instead.
> the fix would be to add an explicit type annotation on the source of the problem.

So to fix it, I'd suggest explicitly annotating public properties of this class:

```typescript
import { Question } from '@serenity-js/core'
import { Element, ElementArray } from 'webdriverio';

// ...

    GenericButton = (linkText: string): Question<Promise<Element<'async'>>> =>
        Target.the(`button with linkText ${linkText}`).located(by.linkText(linkText));
    

    GetingStartedButtons: Question<Promise<ElementArray>> = 
        Target.all(`buttons for getting started`).located(by.linkText(this.t('START_BUTTON'))).first();
```

Let me know if this helps!

**Comment by viper3400** [comment]
Thanks for your help, @jan-molak.

First point is, that I was a bit confused by the ```@typescript-eslint/explicit-module-boundary-types``` lint rule. We haven't had this rule in our projects for now.

Second, I wonder why this worked with Protractor. If I apply my example to the mocha-protractor-template compiler won't complain at all.

But okay, so this would mean some small additional migration effort.

Seems, instead of ```Question<Promise<Element<'async'>>>``` one can use ```TargetElement``` which could be imported from ```@serenity-js/webdriverio``` (and avoid importing from ```webdriverio```)

Still, this applies not in any case:

```typescript
    GenericButtonsWorks: Question<Promise<ElementArray>> = Target.all(`buttons for getting started`).located(by.linkText(this.t('START_BUTTON')));    

    GenericButtonWorks = (linkText: string): TargetElement => Target.the(`button with linkText ${linkText}`).located(by.linkText(linkText));
    GenericButtonWorksAsWell = (linkText: string): Question<Promise<Element<'async'>>> => Target.the(`button with linkText ${linkText}`).located(by.linkText(linkText));

    GettingStartedButtonWorks: Question<Promise<Element<'async'>>> = Target.all(`buttons for getting started`).located(by.linkText(this.t('START_BUTTON'))).first();
    //GetingStartedButtonWontWork: TargetElement = Target.all(`buttons for getting started`).located(by.linkText(this.t('START_BUTTON'))).first();
```
I wonder if we can get rid of importing from webdriverio, directly?!

**Comment by jan-molak** [comment]
> Still, this applies not in any case

The first case works because`TargetElement` is a subtype of `Question<Promise<Element<'async'>>>` ([`TargetElement extends Question<Promise<Element<'async'>>>`](https://github.com/serenity-js/serenity-js/blob/032a7f9f5380d6bb2c2167b47d6188af3b47a84d/packages/webdriverio/src/screenplay/questions/targets.ts#L345)):

```typescript
GenericButtonWorks = (linkText: string): TargetElement => 
    Target.the(`button with linkText ${linkText}`).located(by.linkText(linkText));

GenericButtonWorksAsWell = (linkText: string): Question<Promise<Element<'async'>>> =>|
    Target.the(`button with linkText ${linkText}`).located(by.linkText(linkText));   
```

The second case doesn't work because we're filtering a [`List`](https://serenity-js.org/modules/core/class/src/screenplay/questions/List.ts~List.html) to retrieve a specific item (note the call to `first()`):

```typescript
GettingStartedButtonWorks: Question<Promise<Element<'async'>>> = 
    Target.all(`buttons for getting started`).located(by.linkText(this.t('START_BUTTON')))
        .first();

GetingStartedButtonWontWork: TargetElement = 
    Target.all(`buttons for getting started`).located(by.linkText(this.t('START_BUTTON')))
        .first();
```

Above, `.first()` is typed to return `Question<Promise<Element<'async'>>`, so TypeScript can't cast that to a subtype of `TargetElement` (see [`ElementArrayListAdapter`](https://github.com/serenity-js/serenity-js/blob/032a7f9f5380d6bb2c2167b47d6188af3b47a84d/packages/webdriverio/src/screenplay/questions/lists.ts#L42), so `Promise<Element<'async'>>`).

Thinking about it, I wonder if it should actually stay this way... 🤔 

> I wonder if we can get rid of importing from webdriverio, directly?!

Yeah, that would be more intuitive, wouldn't it...

I guess we'd need to:
- change [`ListAdapter` interface](https://serenity-js.org/modules/core/file/src/screenplay/questions/lists/ListAdapter.ts.html) to return `Question<Item_Return_Type>` rather than `Item_Return_Type` and `Question<Collection_Return_Type>` instead of `Collection_Return_Type`
- change [`ArrayListAdapter`](https://serenity-js.org/modules/core/class/src/screenplay/questions/lists/ArrayListAdapter.ts~ArrayListAdapter.html) to implement the modified interface
- change [`ElementArrayFinderListAdapter`](https://serenity-js.org/modules/protractor/class/src/screenplay/questions/lists/ElementArrayFinderListAdapter.ts~ElementArrayFinderListAdapter.html) to implement the modified interface
- change [`ElementArrayListAdapter`](https://serenity-js.org/modules/webdriverio/class/src/screenplay/questions/lists.ts~ElementArrayListAdapter.html) to implement the modified interface
- change [`List`](https://serenity-js.org/modules/core/class/src/screenplay/questions/List.ts~List.html) to not re-package the `Questions` returned by the modified `ListAdapters`

**Comment by jan-molak** [comment]
Done as part of Serenity/JS 3.0 and deprecation of `Target` in favour of `PageElement`
